bcgov/emcr-ess-mod

- suppliers/src/UI/embc-supplier/src/app/app-routing.module.ts
- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.html
- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.scss
- suppliers/src/UI/embc-supplier/src/app/service/supplier.service.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.scss
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.scss
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.scss
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/supplierSubmission.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/supplierSubmission.component.scss
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/supplierSubmission.component.ts
- suppliers/src/UI/embc-supplier/src/styles/styles.scss
-Completed integration with invoices and receipts components
- changed the path name from supplier to submission
- Added the ability to calculate sum
- ability to calculate grand total for both invoices and receipts
- ability to remove referrals
> Added referral component

- suppliers/src/UI/embc-supplier/src/app/app.component.ts
- suppliers/src/UI/embc-supplier/src/app/review/review.component.html
- suppliers/src/UI/embc-supplier/src/app/service/globalConstants.ts
- suppliers/src/UI/embc-supplier/src/app/service/supplier.service.ts
- suppliers/src/UI/embc-supplier/src/app/service/supplierHttp.service.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/supplierSubmission.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/supplierSubmission.component.ts
-Attachment submission
-data reload
-receipt number for submission
-typeahead fields
> Fixed issues

- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.html
- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.ts
- suppliers/src/UI/embc-supplier/src/app/core/components/modal/invoiceModal.component.ts
- suppliers/src/UI/embc-supplier/src/app/core/components/modal/receiptModal.component.ts
- suppliers/src/UI/embc-supplier/src/app/core/components/toasts/toasts.component.html
- suppliers/src/UI/embc-supplier/src/app/core/components/toasts/toasts.component.ts
- suppliers/src/UI/embc-supplier/src/app/core/core.module.ts
- suppliers/src/UI/embc-supplier/src/app/core/directives/DragDrop.directive.ts
- suppliers/src/UI/embc-supplier/src/app/service/customValidation.service.ts
- suppliers/src/UI/embc-supplier/src/app/service/data.service.ts
- suppliers/src/UI/embc-supplier/src/app/service/supplierHttp.service.ts
- suppliers/src/UI/embc-supplier/src/app/service/toast.service.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.scss
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.scss
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.scss
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/supplierSubmission.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/supplierSubmission.component.ts
- suppliers/src/UI/embc-supplier/src/styles/styles.scss
EMBCESSMOD-526: Check for zero size attachment
EMBCESSMOD-539: Fields that needs bold
EMBCESSMOD-537: Missing text
EMBCESSMOD-531: Size validation
EMBCESSMOD-538: Currency symbol
> Bug fixes & new functionalities

- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/invoice/invoice.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/receipt/receipt.component.ts
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/referral/referral.component.html
- suppliers/src/UI/embc-supplier/src/app/supplierSubmission/supplierSubmission.component.html
EMBCESSMOD-526: Fixed browse with same file name
EMBCESSMOD-532: Restrict deletion
> Jira fixes

- evacuees/src/UI/embc-evacuee/src/app/core/components/address-forms/bc-address/bc-address.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/components/address-forms/bc-address/bc-address.component.ts
- evacuees/src/UI/embc-evacuee/src/app/core/components/address-forms/can-address/can-address.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/components/address-forms/other-address/other-address.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/components/address-forms/usa-address/usa-address.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/components/evacuee-profile-forms/address/address.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/components/evacuee-profile-forms/address/address.component.ts
- evacuees/src/UI/embc-evacuee/src/app/core/components/evacuee-profile-forms/secret/secret.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/components/evacuee-profile-forms/secret/secret.component.scss
- evacuees/src/UI/embc-evacuee/src/app/core/model/createProfile.model.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/componentCreation.service.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/formCreation.service.ts
Incorporated feedback for EMBCESSMOD-723 as well
> EMBCESSMOD-721: Primary Residence & Mailing Address Page UI

- evacuees/src/UI/embc-evacuee/src/app/core/components/evacuee-profile-forms/secret/secret.component.html
- evacuees/src/UI/embc-evacuee/src/app/profile/profile.component.html
- evacuees/src/UI/embc-evacuee/src/app/profile/profile.component.ts
> EMBCESSMOD-723 

- evacuees/src/UI/embc-evacuee/src/app/core/components/address-forms/bc-address/bc-address.component.ts
- evacuees/src/UI/embc-evacuee/src/app/core/components/address-forms/can-address/can-address.component.ts
- evacuees/src/UI/embc-evacuee/src/app/core/components/address-forms/usa-address/usa-address.component.ts
- evacuees/src/UI/embc-evacuee/src/app/core/components/evacuee-profile-forms/address/address.component.ts
- evacuees/src/UI/embc-evacuee/src/app/core/components/needs-assessment-forms/evac-address/evac-address.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/components/needs-assessment-forms/evac-address/evac-address.component.scss
- evacuees/src/UI/embc-evacuee/src/app/profile/profile.component.spec.ts
- evacuees/src/UI/embc-evacuee/src/app/profile/profile.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedRoutes/needs-assessment/needs-assessment.component.ts
1. Fixed invalid validation issues of address autocompletes
> Navigation between profile and needs assessment

- evacuees/src/UI/embc-evacuee/src/app/core/model/problemDetail.ts
- evacuees/src/UI/embc-evacuee/src/app/core/model/profile.model.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/api/registration.service.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/customValidation.service.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/dataSubmission.service.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/profile/profile.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/profile/profile.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/review/review.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/review/review.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/view-auth-profile/view-auth-profile.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/view-auth-profile/view-auth-profile.component.spec.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/view-auth-profile/view-auth-profile.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/evacuee-profile-forms/contact-info/contact-info.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/evacuee-profile-forms/contact-info/contact-info.component.ts
EMBCESSMOD-882
EMBCESSMOD-872
EMBCESSMOD-722
EMBCESSMOD-871
> Create-profile API integration and Bug fixes

- evacuees/src/UI/embc-evacuee/src/app/core/model/profile.model.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/globalConstants.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/review/review.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/evacuee-profile-forms/contact-info/contact-info.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/evacuee-profile-forms/contact-info/contact-info.component.ts
-Disabled button when submission in progress
> Bug Fixes: EMBCESSMOD-728,722,868

- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/evac-address/evac-address.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/evac-address/evac-address.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/person-detail-form/person-detail-form.component.html
EMBCESSMOD-724: Fix to avoid copying Primary Address on BC Evacuation Address when Primary Address is not a BC Address
EMBCESSMOD-725: Fix to continue application when Family Member addition is canceled.
> EMBCESSMOD-724, EMBCESSMOD-725

- evacuees/src/UI/embc-evacuee/src/app/core/model/needs.model.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/evac-address/evac-address.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/pets/pets.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/pets/pets.component.ts
EMBCESSMOD-725: Bugfix on family members. When family members are added and the user goes back to the profile section, family members are erased when a new one is added.
EMBCESSMOD-726: Bugfix on pets. When the user attends to add a second pet and then cancels the action, the form doesn't allow to continue with the process.
> EMBCESSMOD-725, EMBCESSMOD-726

- evacuees/src/UI/embc-evacuee/src/app/core/model/needs-assessment.ts
- evacuees/src/UI/embc-evacuee/src/app/core/model/needs.model.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/dataUpdation.service.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/review/review.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/identify-needs/identify-needs.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/pets/pets.component.ts
EMBCESSMOD-726: New bugfix. Updates validation rules for pets form.
EMBCESSMOD-1060: Update on APIs and UI changes regarding needs assessment
> EMBCESSMOD-726, EMBCESSMOD-1060

- evacuees/src/UI/embc-evacuee/src/app/core/model/needs.model.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/customValidation.service.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/globalConstants.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/routeGuards.service.ts
- evacuees/src/UI/embc-evacuee/src/app/non-verified-registration/non-verified-registration-routing.module.ts
- evacuees/src/UI/embc-evacuee/src/app/non-verified-registration/non-verified-registration.module.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/review/review.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/pet-form/pet-form.component.html
EMBCESSMOD-728: Fix on birthday dates format on family members and displayed answer on the insurance option on the Review Form before submission. 
EMBCESSMOD-729: added canDeactivate guard to avoid users to go back to the profile and assessment forms after submitting a new file as non-verified registrant. 
EMBCESSMOD-1029: refactoring on Pets form. When pets are added, the quantity data is an input that only allows numbers from 1 to 999. Refactor was made to fit the new backend update.
> EMBCESSMOD-728, EMBCESSMOD-729, EMBCESSMOD-1029

- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/collection-notice/collection-notice.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/collection-notice/collection-notice.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/identify-needs/identify-needs.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/pets/pets.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/pets/pets.component.ts
EMBCESSMOD-726: inserting additional fixes to Pets form: when the add pet form is displayed, the delete and edit buttons from inserted records are disabled. The behaviour of allowing insertion of household members with required empty info is fixed as well.
EMBCESSMOD-1060: Changes on static descriptions on needs assessments and Create Profile pages according to recent wireframes.
EMBCESSMOD-1016: Commenting on the checkbox from Collection notice page to match recent wireframes.
> EMBCESSMOD-726, EMBCESSMOD-1060, EMBCESSMOD-1016

- evacuees/src/UI/embc-evacuee/src/app/core/components/dialog/dialog.component.scss
- evacuees/src/UI/embc-evacuee/src/app/core/services/dataSubmission.service.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/globalDialog.service.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/profile/profile.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/review/review.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/view-auth-profile/view-auth-profile.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/view-auth-profile/view-auth-profile.component.ts
EMBCESSMOD-1114: Integration API - Create Profile
EMBCESSMOD-880: Integration API - new needs assessment profile 
EMBCESSMOD-1023: Submission complete Pop-up
> EMBCESSMOD-1114, EMBCESSMOD-880, EMBCESSMOD-1023

- evacuees/src/API/EMBC.Registrants.API/EMBC.Registrants.API.csproj
- evacuees/src/API/EMBC.Registrants.API/ProfilesModule/API.cs
- evacuees/src/API/EMBC.Registrants.API/ProfilesModule/ProfilesConflictDetector.cs
- evacuees/src/API/EMBC.Registrants.API/Startup.cs
- evacuees/src/API/EMBC.Tests.Integration.Registrants.API/EMBC.Tests.Integration.Registrants.API.csproj
- evacuees/src/API/EMBC.Tests.Unit.Registrants.API/EMBC.Tests.Unit.Registrants.API.csproj
- evacuees/src/API/EMBC.Tests.Unit.Registrants.API/Profiles/ConflictTests.cs
> fixed serialization issue with conflicts

- evacuees/src/UI/embc-evacuee/src/app/app.module.ts
- evacuees/src/UI/embc-evacuee/src/app/core/components/dialog/dialog.component.scss
- evacuees/src/UI/embc-evacuee/src/app/core/model/profile.model.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/allowNavigation.guard.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/dialog.service.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/dashboard/dashboard.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/dashboard/dashboard.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/profile/profile-mapping.service.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/evacuee-profile-forms/contact-info/contact-info.component.ts
EMBCESSMOD-1019: Implementation of the new contact-info page according to new changes.
EMBCESSMOD-1023: fixing bugs from verified-registrant when a new evacuation file is created and a pop-up is displayed.
> EMBCESSMOD-1019, EMBCESSMOD-1023

- evacuees/src/UI/embc-evacuee/src/app/core/components/dialog/dialog.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/components/dialog/dialog.component.scss
- evacuees/src/UI/embc-evacuee/src/app/core/layout/header/header.component.html
- evacuees/src/UI/embc-evacuee/src/app/core/layout/header/header.component.scss
- evacuees/src/UI/embc-evacuee/src/app/core/layout/header/header.component.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/data.service.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/dataUpdation.service.ts
- evacuees/src/UI/embc-evacuee/src/app/core/services/dialog.service.ts
- evacuees/src/UI/embc-evacuee/src/app/non-verified-registration/non-verified-registration.component.spec.ts
- evacuees/src/UI/embc-evacuee/src/app/non-verified-registration/non-verified-registration.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/dashboard/dashboard.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/evacuation-file/evacuation-file-list/evacuation-file-list.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/evacuation-file/evacuation-file.service.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/file-submission/file-submission.component.spec.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/file-submission/file-submission.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.spec.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/needs-assessment/needs-assessment.service.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/profile/profile-mapping.service.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/restriction/restriction.component.spec.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/restriction/restriction.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/components/review/review.component.html
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/evac-address/evac-address.component.ts
- evacuees/src/UI/embc-evacuee/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.html
- evacuees/src/UI/embc-evacuee/src/app/verified-registration/verified-registration.component.spec.ts
- evacuees/src/UI/embc-evacuee/src/app/verified-registration/verified-registration.component.ts
- evacuees/src/UI/embc-evacuee/src/styles/styles.scss
Reverts bcgov/embc-ess-mod#273
> Revert "EMBCESSMOD-1084, EMBCESSMOD-728, EMBCESSMOD-1010, EMBCESSMOD-1082, EMBCESSMOD-1023"

- evacuees/src/API/EMBC.Registrants.API/EvacuationsModule/API.cs
- evacuees/src/API/EMBC.Registrants.API/EvacuationsModule/EvacuationAutoMapperProfile.cs
- evacuees/src/API/EMBC.Registrants.API/EvacuationsModule/EvacuationManager.cs
- evacuees/src/API/EMBC.Registrants.API/EvacuationsModule/EvacuationRepository.cs
- evacuees/src/API/EMBC.Registrants.API/ProfilesModule/ProfileAutoMapperProfile.cs
- evacuees/src/API/EMBC.Registrants.API/RegistrationsModule/RegistrationManager.cs
- evacuees/src/API/EMBC.Registrants.API/Shared/DTOs.cs
- evacuees/src/API/EMBC.ResourceAccess.Dynamics/DynamicsClientContextEx.cs
- evacuees/src/API/EMBC.Tests.Integration.Registrants.API/DynamicsRegistrationPersistenceTests.cs
- evacuees/src/API/EMBC.Tests.Integration.Registrants.API/Evacuations/EvacuationTests.cs
Adds Household Member DTO and allows editing of Household Member lists.
> EMBCESSMOD-1224 - Fixes issue when submitting a new evacuation file for BCSC registered user.

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/add-community/add-community.component.html
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/add-community/add-community.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/add-community/add-community.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-list/assigned-community-list-data.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-list/assigned-community-list.component.html
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-list/assigned-community-list.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-list/assigned-community-list.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-management/assigned-community-management.component.html
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-management/assigned-community-management.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-review/assigned-community-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-table/assigned-community-table.component.html
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-table/assigned-community-table.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-table/assigned-community-table.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-table/assigned-community-table.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-table/assigned-community-table.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/team/team-member-detail/team-member-detail.component.html
- responders/src/UI/embc-responder/src/app/feature-components/team/team-member-management/team-member-management.component.ts
- responders/src/UI/embc-responder/src/app/shared/shared.module.ts
- code cleanup and added comments
> Refactoring- Removed data table from shared module

- suppliers/src/UI/embc-supplier/src/app/core/services/authentication.service.ts
testing auth config is set correctly
> add additional logging to authentication service

- responders/src/UI/embc-responder/src/app/core/services/authorization.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-id-verify/evacuee-id-verify.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-name-search/evacuee-name-search.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.ts
-Profile results
-ESS Files results
> Search result display

- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/team/edit-team-member/edit-team-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/team/edit-team-member/edit-team-member.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/team/edit-team-member/edit-team-member.component.ts
- responders/src/UI/embc-responder/src/styles/_variables.scss
> EMBCESSMOD-1334

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.module.ts
-evacuation-details
-animals
-review and save
> EMBCESSMOD-1406: empty ess-file components

- responders/src/UI/embc-responder/src/app/core/models/tab.model.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/collection-notice/collection-notice.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/collection-notice/collection-notice.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/collection-notice/collection-notice.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-profile/step-create-profile-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-profile/step-create-profile.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-profile/step-create-profile.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-profile/step-create-profile.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-profile/step-create-profile.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-profile/step-create-profile.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.service.ts
- Wizard component adjustments
- set status for step and tab
> EMBCESSMOD-1406: Profile Step

- ess/openshift/Templates/ess-backend.template.yml
- ess/openshift/Templates/ess-backend.yml.params.template
- ess/src/API/EMBC.ESS.Utilities.Dynamics/EMBC.ESS.Utilities.Dynamics.csproj
- ess/src/API/EMBC.ESS/EMBC.ESS.csproj
- ess/src/API/EMBC.Tests.Integration.ESS/EMBC.Tests.Integration.ESS.csproj
- ess/src/API/EMBC.Tests.Unit.ESS/EMBC.Tests.Unit.ESS.csproj
- evacuees/openshift/Templates/registrants-portal.template.yml
- evacuees/openshift/Templates/registrants-portal.yml.params.template
- evacuees/src/API/EMBC.Registrants.API/EMBC.Registrants.API.csproj
- evacuees/src/API/EMBC.Tests.Integration.Registrants.API/WebAppTestBase.cs
- evacuees/src/API/EMBC.Tests.Unit.Registrants.API/EMBC.Tests.Unit.Registrants.API.csproj
- responders/openshift/Templates/responders-portal.template.yml
- responders/src/API/EMBC.Responders.API/EMBC.Responders.API.csproj
- responders/src/API/EMBC.Tests.Unit.Responders.API/EMBC.Tests.Unit.Responders.API.csproj
openshift templates and nuget packages
> various fixes

- ess/src/API/EMBC.ESS/Utilities/Messaging/DispatcherService.cs
- evacuees/src/API/EMBC.Registrants.API/Utils/DispatcherClientEx.cs
- responders/src/API/EMBC.Responders.API/Startup.cs
- responders/src/API/EMBC.Responders.API/Utilities/DispatcherClientEx.cs
> Fix - type resolution between grpc client and server

- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/security-questions/security-questions.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/security-questions/security-questions.service.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog/dialog.component.scss
Added descriptions for Security Question methods, fixed Modal Close visuals and removed extra Select label
> EMBCESSMOD-1471 - documentation and quick visual fixes

- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
update registrant profile mapping with new security questions
> EMBCESSMOD-1475 - Responders API Registrant Profile mapping updated

- ess/src/API/EMBC.ESS.Shared.Contracts/Submissions/Search.cs
- ess/src/API/EMBC.ESS.Shared.Contracts/Submissions/Submissions.cs
- ess/src/API/EMBC.ESS/Managers/Submissions/Mappings.cs
- ess/src/API/EMBC.ESS/Managers/Submissions/SubmissionsManager.cs
- ess/src/API/EMBC.ESS/Resources/Cases/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/EvacuationRepository.cs
- ess/src/API/EMBC.ESS/Resources/Cases/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/Mappings.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
- ess/src/API/EMBC.Tests.Unit.ESS/Contacts/FakeGenerator.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
Add flags to indicate if security answers should be saved or not, to prevent inadvertently wiping real answers with masked ones.
> EMBCESSMOD-1675 - Security questions and phrase verification

- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.ts
- New shell components for matched ess files and possible matched ess files
> EMBCESSMOD-1697

- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.Search.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
update upsert registrant profile to separate create and update functions. Add Get for Registrant Profile by id. Add Get File by id, and a placeholder for update file
> EMBCESSMOD-1602 - Registrant Profile CRUD updates (...no D)

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/needs/needs.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/needs/needs.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-ess-file/step-create-ess-file.service.ts
With Needs Assessment options as strings, we can clear up the uncertainty of "null" meaning both "not set" and "user has selected I'm Not Sure"
While working on Review tab, discovered and fixed some fields that weren't being set correctly, as well as some other minor cleanup.
> EMBCESSMOD-1574: Review Tab UI, Step 2 fixes

- ess/src/API/EMBC.ESS.Shared.Contracts/EMBC.ESS.Shared.Contracts.csproj
- ess/src/API/EMBC.ESS.Shared.Contracts/Submissions/Registrants.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/ContactRepository.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/Mappings.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
- ess/src/API/EMBC.Tests.Unit.ESS/Contacts/FakeGenerator.cs
- ess/src/API/EMBC.Tests.Unit.ESS/Contacts/MappingTests.cs
Add City field to backend Address for RegistrantProfile/Contact. Updated mappings and tests accordingly.
Also updated State/Province Link to handle the case that the state/province is null.
> EMBCESSMOD-1770 - Backend updates to separate city/community fields

- responders/src/UI/embc-responder/src/app/app.component.ts
- responders/src/UI/embc-responder/src/app/core/services/locations.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/responder-access/responder-access.component.ts
> Responders

- responders/src/UI/embc-responder/src/app/core/models/evacuee-profile.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-session.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-profile/step-create-profile.service.ts
- Map communityId to correct value in wizard and profile api's
- Added missing mappings for profile on UI
> EMBCESSMOD-1756

- ess/src/API/EMBC.ESS/Resources/Contacts/ContactRepository.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/Mappings.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Resources/ContactTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.Search.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
updates to contact repo to allow deleting link for jurisdiction and state/province. 
Mappings updated to also allow wiping city and stateprovince fields. 
Fixed missing return mappings for registrant
> EMBCESSMOD-1770 - Fix missing fields for Registrant.

- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
fix mapping error with get security phrase
> EMBCESSMOD-1789

- responders/src/UI/embc-responder/src/app/app-routing.module.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-session.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-ess-file/step-create-ess-file.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-create-profile/step-create-profile.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-activate.guard.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.service.ts
1. Created activate guard for wizard access
2. Modified evacuee session service to store essFileNumber
> EMBCESSMOD-1646

- responders/src/UI/embc-responder/src/app/core/models/tab.model.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-evacuee-profile/step-evacuee-profile.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.service.ts
- responders/src/UI/embc-responder/src/styles/styles.scss
- Added tab config for notes section
- Added routing for notes
- Added parent component to list notes and add notes
> EMBCESSMOD-1849: Added details to notes step

- responders/src/UI/embc-responder/src/app/core/api/models/evacuation-file.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.service.ts
- responders/src/UI/embc-responder/src/styles/styles.scss
- Added list notes component
- Added integration to get notes from evacuation file
> EMBCESSMOD-1849, EMBCESSMOD-1850

- responders/src/UI/embc-responder/src/app/core/models/dialog-content.model.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-evacuee-profile/step-evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/information-dialog/information-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/verify-evacuee-dialog/verify-evacuee-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/verify-evacuee-dialog/verify-evacuee-dialog.component.scss
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/verify-evacuee-dialog/verify-evacuee-dialog.component.ts
EMBCESSMOD-1857: modified the evacuee details component to support editions on unverified evacuees
EMBCESSMOD-1858: modified the evacuee details component to support editions on verified evacuees. Changes on verify-evacuee-dialog component to cover unlock fields case on edit profile.
> EMBCESSMOD-1857, EMBCESSMOD-1858

- responders/src/UI/embc-responder/src/app/core/api/models.ts
- responders/src/UI/embc-responder/src/app/core/api/models/needs-assessment.ts
- responders/src/UI/embc-responder/src/app/core/api/models/note.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- Added the UI to create notes
- Added the ability to cancel create note
- Added mapping for list api integration
> Notes: EMBCESSMOD-1851, 1853

- responders/src/UI/embc-responder/src/app/core/api/services/registrations.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.service.ts
Integration with save notes api
> EMBCESSMOD-1852

- ess/src/API/EMBC.ESS/Resources/Contacts/ContactRepository.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/Contract.cs
- registrants/src/API/EMBC.Registrants.API/Mappers/Mappings.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
Improvements to HandleSaveContact
> EMBCESSMOD-1806: Hookup set registrant verified on Responders API. 

- ess/src/API/EMBC.ESS/Managers/Submissions/SubmissionsManager.cs
- ess/src/API/EMBC.ESS/Resources/Cases/CaseRepository.cs
- ess/src/API/EMBC.ESS/Resources/Cases/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/EvacuationRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
remove separate update security phrase function, it was completely unnecessary
> EMBCESSMOD-1873: 

- responders/src/UI/embc-responder/src/app/core/services/authorization.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.service.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog/dialog.component.ts
- responders/src/UI/embc-responder/src/styles/styles.scss
- Created Edit note UI
- Integrated with edit api
- Created Hide/Unhide UI'
- Integrated with hide/unhide api
> EMBCESSMOD-1966, 2014, 1967, 2013

- ess/src/API/EMBC.ESS/Resources/Contacts/Mappings.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
add postal code to contact mappings so it can actually be saved and edited
> EMBCESSMOD-1844: bug fix for saving postal codes

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-overview/ess-file-overview-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-overview/ess-file-overview.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-overview/ess-file-overview.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-overview/ess-file-overview.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-overview/ess-file-overview.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-overview/ess-file-overview.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.scss
> EMBCESSMOD-2035, 2056

- responders/src/UI/embc-responder/src/app/core/models/evacuation-file-summary.model.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.ts
EMBCESSMOD-2067: ESS Files list on Profile Dashboard - API Integration and UI implementation
> EMBCESSMOD-2067

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-evacuee-profile/step-evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-activate.guard.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-adapter.service.ts
EMBCESSMOD-2141: Wizard Navigation from ESS File Dashboard
EMBCESSMOD-2142: Wizard Data loading
EMBCESSMOD-214: Wizard Status Tab configuration
EMBCESSMOD-2144: Evacuation Details component updates
> EMBCESSMOD-2141, EMBCESSMOD-2142, EMBCESSMOD-2143, EMBCESSMOD-2144

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-notes/ess-file-notes-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-notes/ess-file-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-notes/ess-file-notes.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-notes/ess-file-notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-notes/ess-file-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-notes/ess-file-notes.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.ts
- Created Notes section ess file dashboard
- Integrated with the get notes api
> EMBCESSMOD-2117, 2118

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-adapter.service.ts
EMBCESSMOD-2148: Update Security Phrase component
EMBCESSMOD-2149: Update Save & Review component
EMBCESSMOD-2150: Edit ESS File API Integration
> EMBCESSMOD-2148, EMBCESSMOD-2149, EMBCESSMOD-2150

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-adapter.service.ts
- Primary member shows up on tab, grey BG, no buttons
- Updated logic to keep this member separate from others
- Fixed issues with clearing members from list
- Renamed some variables on Component HTML files to more accurately reflect objects being worked with
> EMBCESSMOD-2052 - Primary Household Member

- responders/src/UI/embc-responder/src/app/core/api/models.ts
- responders/src/UI/embc-responder/src/app/core/api/models/registrant-link-request.ts
- responders/src/UI/embc-responder/src/app/core/api/services/registrations.service.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-session.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-overview/ess-file-overview.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/file-dashboard-verify-dialog/file-dashboard-verify-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/file-dashboard-verify-dialog/file-dashboard-verify-dialog.component.scss
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/file-dashboard-verify-dialog/file-dashboard-verify-dialog.component.ts
- responders/src/UI/embc-responder/src/app/shared/shared.module.ts
- Created household members component
- Integrated with the matched profile api on panel expansion
- Created View Profile functionality with verify popup
> EMBCESSMOD-2119, 2120, 2196

- ess/src/API/EMBC.ESS.Shared.Contracts/EMBC.ESS.Shared.Contracts.csproj
- ess/src/API/EMBC.ESS.Shared.Contracts/Submissions/Submissions.cs
- ess/src/API/EMBC.ESS/Engines/Search/Contract.cs
- ess/src/API/EMBC.ESS/Engines/Search/SearchEngine.cs
- ess/src/API/EMBC.ESS/Managers/Submissions/SubmissionsManager.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/ContactRepository.cs
- ess/src/API/EMBC.ESS/Resources/Contacts/Contract.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
Add tests for search matching
Add backend functionality to link registrant and household member
> EMBCESSMOD-2171, EMBCESSMOD-2172

- responders/src/UI/embc-responder/src/app/core/models/evacuation-file.model.ts
- responders/src/UI/embc-responder/src/app/core/models/fileLinkRequest.model.ts
- responders/src/UI/embc-responder/src/app/core/models/multipleLinkRegistrant.model.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-session.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/profile-security-questions/profile-security-questions.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/profile-security-questions/profile-security-questions.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/verify-evacuee-dialog/verify-evacuee-dialog.component.html
- Created profile linking flow for single profile match
- Created profile linking flow for multiple profile match
- Made changes to security questions to allow for file linking
> EMBCESSMOD-2206, 2208

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/registrant-link-dialog/registrant-link-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/registrant-link-dialog/registrant-link-dialog.component.scss
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/registrant-link-dialog/registrant-link-dialog.component.ts
- responders/src/UI/embc-responder/src/app/shared/shared.module.ts
- Dialog to list the multiple matched profile results
> EMBCESSMOD-2206

- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/EvacuationRepository.cs
fix for loading household member verified/restricted fields at the file level
> EMBCESSMOD-2191

- responders/src/UI/embc-responder/src/app/core/services/evacuee-session.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-evacuee-profile/step-evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-activate.guard.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-adapter.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-data.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-deactivate.guard.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.service.ts
- Create profile for household member functionality
> EMBCESSMOD-2207-Household members create profile

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-adapter.service.ts
EMBCESSMOD-2149: Review component - Complete ESS File
EMBCESSMOD-2055: Household Members bugs fix
EMBCESSMOD-2189: Review component - Review ESS File
> EMBCESSMOD-2149, EMBCESSMOD-2055, EMBCESSMOD-2189

- responders/src/UI/embc-responder/src/app/feature-components/responder-access/responder-access-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/list-suppliers/list-suppliers-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/list-suppliers/list-suppliers.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/list-suppliers/list-suppliers.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/list-suppliers/list-suppliers.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/list-suppliers/list-suppliers.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/list-suppliers/list-suppliers.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management.module.ts
- responders/src/UI/embc-responder/src/app/shared/components/toggle-side-nav/toggle-side-nav.component.html
- responders/src/UI/embc-responder/src/app/shared/components/top-nav-menu/top-nav-menu.component.html
- Created Navigation for supplier mgmt.
- Create empty component for list suppliers
> EMBCESSMOD-2235

- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management.component.ts
-Add Supplier flow
-Add supplier form
-New supplier form
> Supplier Mgmt

- responders/src/UI/embc-responder/src/app/core/models/evacuation-file-search-result.model.ts
- responders/src/UI/embc-responder/src/app/core/services/ess-file.service.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/core/services/evacuee-session.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/essfile-security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/essfile-security-phrase.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.ts
EMBCESSMOD-2121:Match possible ESSFiles feature
> EMBCESSMOD-2121

- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/EvacuationRepository.cs
> bug fix for update ess file

- ess/src/API/EMBC.ESS.Shared.Contracts/EMBC.ESS.Shared.Contracts.csproj
- ess/src/API/EMBC.ESS.Shared.Contracts/Submissions/Suppliers.cs
- ess/src/API/EMBC.ESS/Managers/Submissions/Mappings.cs
- ess/src/API/EMBC.ESS/Managers/Submissions/SubmissionsManager.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/Configuration.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/SupplierRepository.cs
- ess/src/API/EMBC.ESS/Startup.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
add supplier repository and setup supplier query
> EMBCESSMOD-2237

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/core/services/suppliers.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/edit-supplier/edit-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-list.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-list.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-table/suppliers-table.component.ts
EMBCESSMOD-2270: change supplier's status on main supplier's list
> EMBCESSMOD-2270

- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
- responders/src/API/EMBC.Responders.API/Controllers/SuppliersController.cs
> EMBCESSMOD-2237, EMBCESSMOD-2361, EMBCESSMOD-2414

- responders/src/UI/embc-responder/src/app/core/api/models.ts
- responders/src/UI/embc-responder/src/app/core/api/models/lodging-billeting-referral.ts
- responders/src/UI/embc-responder/src/app/core/api/models/lodging-group-referral.ts
- responders/src/UI/embc-responder/src/app/core/api/models/supplier-list-item.ts
- responders/src/UI/embc-responder/src/app/core/api/models/support.ts
- responders/src/UI/embc-responder/src/app/core/api/services/suppliers.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.module.ts
- responders/src/UI/embc-responder/src/assets/images/back-arrow.svg
- Created support wizard flow
- Integrated with support category and sub category api's
> EMBCESSMOD-2381, 2448

- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.module.ts
> EMBCESSMOD-2382

- responders/src/UI/embc-responder/src/app/core/services/suppliers.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/supplier-list-data.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-list.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-table/suppliers-table.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-table/suppliers-table.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.ts
EMBCESSMOD-2324: ESS File Wizard -  Evacuation Details bug
EMBCESSMOD-2314: Mutual Aid List Integration with API
EMBCESSMOD-2269: Main Suppliers List Integration with API
> EMBCESSMOD-2324, EMBCESSMOD-2314, EMBCESSMOD-2269

- responders/src/UI/embc-responder/src/app/core/services/locations.service.ts
- responders/src/UI/embc-responder/src/app/core/services/suppliers.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-exist/supplier-exist.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-exist/supplier-exist.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/supplier-list-data.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-list.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-table/suppliers-table.component.ts
EMBCESSMOD-2267: UI Integration for Main Suppliers Details View
EMBCESSMOD-2416: Navigation for Add Supplier - API Integration with Supplier Exist functionality
EMBCESSMOD-2317: UI Integration for Mutual Aid Details View
> EMBCESSMOD-2267, EMBCESSMOD-2416, EMBCESSMOD-2317

- registrants/src/UI/embc-registrant/src/app/feature-components/edit/edit.service.ts
> EMBCESSMOD-2413

- ess/src/API/EMBC.ESS.Shared.Contracts/EMBC.ESS.Shared.Contracts.csproj
- ess/src/API/EMBC.ESS.Shared.Contracts/Suppliers.cs
- ess/src/API/EMBC.ESS/Managers/Admin/AdminManager.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/SupplierRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Admin/AdminTests.cs
- responders/src/API/EMBC.Responders.API/Controllers/SuppliersController.cs
Backend work for save supplier + Activate/Deactivate
> EMBCESSMOD-2362, EMBCESSMOD-2363

- responders/src/UI/embc-responder/src/app/core/api/services/suppliers.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/core/services/locations.service.ts
- responders/src/UI/embc-responder/src/app/core/services/suppliers.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/add-supplier/add-supplier.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/edit-supplier/edit-supplier.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/edit-supplier/edit-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/edit-supplier/edit-supplier.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/edit-supplier/edit-supplier.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/new-supplier/new-supplier.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-exist/supplier-exist.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-review/supplier-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/supplier-list-data.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-list.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-list.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-table/suppliers-table.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-table/suppliers-table.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/collection-notice/collection-notice.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-evacuee-profile/step-evacuee-profile.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-evacuee-profile/step-evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.service.ts
EMBCESSMOD-2311: API Integration to add new primary supplier.
EMBCESSMOD-2319: API Integration to edit a primary supplier.
EMBCESSMOD-2270: changes on API Integration to activate/deactivate a primary supplier
> EMBCESSMOD-2311, EMBCESSMOD-2319, EMBCESSMOD-2270

- responders/src/UI/embc-responder/src/app/core/models/supplier-list-item.model.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/core/services/locations.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.ts
- Refresh list
- Error handling and loader
> EMBCESSMOD-2520

- registrants/src/UI/embc-registrant/src/app/core/services/security-questions.service.ts
> Registrant portal

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.spec.ts
- Added warning popup on support(back) link
> EMBCESSMOD-2380

- ess/src/API/EMBC.ESS.Shared.Contracts/EMBC.ESS.Shared.Contracts.csproj
- ess/src/API/EMBC.ESS.Shared.Contracts/Suppliers.cs
- ess/src/API/EMBC.ESS/Managers/Admin/AdminManager.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/SupplierRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Admin/AdminTests.cs
include address info for EMBCESSMOD-2538
> Add Remove Supplier Command

- responders/src/UI/embc-responder/src/app/core/api/api.module.ts
- responders/src/UI/embc-responder/src/app/core/api/services.ts
- responders/src/UI/embc-responder/src/app/core/api/services/suppliers.service.ts
- responders/src/UI/embc-responder/src/app/core/api/services/teams.service.ts
- responders/src/UI/embc-responder/src/app/core/services/load-team-list.service.ts
- responders/src/UI/embc-responder/src/app/core/services/suppliers.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-list.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/team/add-team-member/add-team-member.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/team/edit-team-member/edit-team-member.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/team/team-list/team-list.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/team/team-member-detail/team-member-details.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/team/team-member-review/team-member-review.service.ts
EMBCESSMOD-2420: Integration with get Mutual Aid list by ESS Team Name
EMBCESSMOD-2422: Integration with get Mutual Aid list by community name
EMBCESSMOD-2423: Integration Rescind Mutual Aid supplier
> EMBCESSMOD-2420, EMBCESSMOD-2422, EMBCESSMOD-2423

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.component.html
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-detail/supplier-detail.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-management.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/supplier-list-data.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-list.component.ts
- responders/src/UI/embc-responder/src/app/shared/pipes/maskFullAddress.pipe.ts
EMBCESSMOD-2424: Add ESS Team as Mutual Aid
> EMBCESSMOD-2424

- responders/src/UI/embc-responder/src/app/core/models/support-details.model.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/referral-creation.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-billeting/lodging-billeting.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-billeting/lodging-billeting.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-billeting/lodging-billeting.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-group/lodging-group.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-group/lodging-group.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-group/lodging-group.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-hotel-motel/lodging-hotel-motel.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-hotel-motel/lodging-hotel-motel.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/lodging-hotel-motel/lodging-hotel-motel.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.service.ts
- responders/src/UI/embc-responder/src/app/shared/pipes/customPipe.module.ts
- responders/src/UI/embc-responder/src/app/shared/pipes/numberOfNights.pipe.ts
-Added supports for:
1. Hotel/Motel
2. Group Lodging
3. Billeting
> EMBCESSMOD-2297,2295,2296

- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.Supports.cs
hookup void support api and create dummy endpoint for reprint support
> EMBCESSMOD-2398, EMBCESSMOD-2396

- ess/src/API/EMBC.ESS/Managers/Submissions/SubmissionsManager.cs
- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/EvacuationRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
improvements to checking Evacuation File Invariants. Additional checks in manager for LinkRegistrantCommand. Add tests for invariants and update link registrant test for new constraints
> Add some checks to LinkRegistrantCommand

- registrants/src/UI/embc-registrant/src/app/core/model/needs.model.ts
- registrants/src/UI/embc-registrant/src/app/core/model/profile.model.ts
- registrants/src/UI/embc-registrant/src/app/core/services/location.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/edit/edit.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/edit/edit.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/edit/edit.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment-mapping.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/profile/profile-data.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/profile/profile-mapping.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/profile/profile.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/review/review.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/conflict-management/conflict-management.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/conflict-management/conflict-management.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/dashboard/dashboard.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-card/evacuation-card.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-data.service.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-mapping.service.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file.service.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.scss
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
EMBCESSMOD-2529: edit ESS Evacuation File. Adapting new models to the current process.
> EMBCESSMOD-2529

- registrants/src/API/EMBC.Registrants.API/Startup.cs
> EMBCESSMOD-2581

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/reprint-referral-dialog/reprint-referral-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/reprint-referral-dialog/reprint-referral-dialog.component.scss
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/reprint-referral-dialog/reprint-referral-dialog.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/void-referral-dialog/void-referral-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/void-referral-dialog/void-referral-dialog.component.scss
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/void-referral-dialog/void-referral-dialog.component.ts
- responders/src/UI/embc-responder/src/app/shared/shared.module.ts
-Void Referral
-Reprint Referral
> EMBCESSMOD-2397, 2399

- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/ess-file-dialog/ess-file-dialog.component.html
- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/ess-file-dialog/ess-file-dialog.component.scss
- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/ess-file-dialog/ess-file-dialog.component.ts
- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/information-dialog/information-dialog.component.html
- registrants/src/UI/embc-registrant/src/app/core/components/dialog/dialog.component.scss
- registrants/src/UI/embc-registrant/src/app/core/components/dialog/dialog.component.ts
- registrants/src/UI/embc-registrant/src/app/core/services/dialog.service.ts
- registrants/src/UI/embc-registrant/src/app/core/services/disableBack.guard.ts
- registrants/src/UI/embc-registrant/src/app/core/services/globalConstants.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/dashboard/dashboard.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-list/evacuation-file-list.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
EMBCESSMOD-2562: Registrant Portal Dialogs
> EMBCESSMOD-2562

- responders/src/UI/embc-responder/src/app/core/models/support-details.model.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/billeting-delivery/billeting-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/billeting-delivery/billeting-delivery.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/billeting-delivery/billeting-delivery.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/group-lodging-delivery/group-lodging-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/group-lodging-delivery/group-lodging-delivery.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/group-lodging-delivery/group-lodging-delivery.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/clothing/clothing.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/clothing/clothing.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/clothing/clothing.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/incidentals/incidentals.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/incidentals/incidentals.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/incidentals/incidentals.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.service.ts
- Added supports for Incidentals and Clothing
- Fixed supplier address rendering issue
- Fixed supplier delivery for billeting and group lodging
> EMBCESSMOD-2300, 2298

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/referral-creation.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.ts
- Setting of Draft supports (Work In Progress)
> EMBCESSMOD-2410

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/review-support/review-support.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/review-support/review-support.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/review-support/review-support.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/review-support/review-support.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/review-support/review-support.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-data.service.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/process-supports-dialog/process-supports-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/process-supports-dialog/process-supports-dialog.component.scss
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/process-supports-dialog/process-supports-dialog.component.spec.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/process-supports-dialog/process-supports-dialog.component.ts
- responders/src/UI/embc-responder/src/app/shared/shared.module.ts
EMBCESSMOD-2303: Partially implemented Integration with APIs
EMBCESSMOD-2392: UI for Process Supports
> EMBCESSMOD-2303, EMBCESSMOD-2392

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard-routing.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
- Supports section for ess file dashboard
> EMBCESSMOD-2551, 2552

- registrants/src/UI/embc-registrant/src/app/core/layout/header/header.component.html
- registrants/src/UI/embc-registrant/src/app/core/services/allowNavigation.guard.ts
- registrants/src/UI/embc-registrant/src/app/core/services/location.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/profile/profile-mapping.service.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-list/evacuation-file-list.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/evacuee-profile-forms/personal-details/personal-details.component.ts
EMBCESSMOD-1627, EMBCESSMOD-2524, EMBCESSMOD-2527
> EMBCESSMOD-1627, EMBCESSMOD-2524, EMBCESSMOD-2527

- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/EvacuationRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/SubmissionsTests.cs
- registrants/src/API/EMBC.Registrants.API/Controllers/EvacuationsController.cs
- registrants/src/API/EMBC.Registrants.API/Mappers/Mappings.cs
add supports to returned files for Registrants portal. Minor testing fixes.
> EMBCESSMOD-2553: Add supports to registrants API

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.service.ts
- Created filters to filter the supports based on status and type
> EMBCESSMOD-2550

- registrants/src/UI/embc-registrant/src/app/core/services/location.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/profile/profile-mapping.service.ts
EMBCESSMOD-1627: Fix on mapping address from BCSC
> EMBCESSMOD-1627

- responders/src/UI/embc-responder/src/app/app.module.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.module.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.ts
> EMBCESSMOD-2409

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-details/ess-file-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-notes/ess-file-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/add-notes/add-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-data.service.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/file-dashboard-verify-dialog/file-dashboard-verify-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/registrant-link-dialog/registrant-link-dialog.component.html
> EMBCESSMOD-2762, 2720

- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.Files.cs
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/needs/needs.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/delete-confirmation-dialog/delete-confirmation-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/forms/pet-form/pet-form.component.html
-Content updates for ess file wizard
> EMBCESSMOD-2759

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/team/add-team-member/add-team-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/team/add-team-member/add-team-member.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/team/edit-team-member/edit-team-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/team/edit-team-member/edit-team-member.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/team/team-member-review/team-member-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/team/team-member-review/team-member-review.component.scss
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/delete-confirmation-dialog/delete-confirmation-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/top-nav-menu/top-nav-menu.component.html
- responders/src/UI/embc-responder/src/app/shared/components/top-nav-menu/top-nav-menu.component.ts
-Fixed top navigation issue
-Applied content updates for Responder Mgmt
> EMBCESSMOD-2698, 2721

- responders/src/UI/embc-responder/src/app/core/models/tab.model.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/supplier-exist/supplier-exist.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/address/address.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/contact/contact.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/security-questions/security-questions.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-evacuee-profile/step-evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-activate.guard.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.service.ts
- Implemented tab rules for evacuee profile tab
> EMBCESSMOD-2536

- ess/src/API/EMBC.ESS/Managers/Admin/AdminManager.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/SupplierRepository.cs
- ess/src/API/EMBC.ESS/Resources/Team/TeamRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/DynamicsTestData.cs
Improve QueryTeams by AssignedCommunityCode efficiency
> EMBCESSMOD-2961: fix for getting list of suppliers by task not filtering inactive suppliers

- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-adapter.service.ts
> EMBCESSMOD-2992

- ess/src/API/EMBC.ESS/Resources/Cases/Evacuations/Mappings.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Admin/AdminTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/DynamicsTestData.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Resources/ContactTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Resources/EvacuationTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Resources/TeamRepositoryTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/EvacuationFileTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/RegistrantTests.cs
> EMBCESSMOD-2736: update mapping of pet fields from needs assessment to ess file. 

- ess/src/API/EMBC.ESS.Shared.Contracts/EMBC.ESS.Shared.Contracts.csproj
- ess/src/API/EMBC.ESS.Shared.Contracts/Submissions/Search.cs
- ess/src/API/EMBC.ESS.Shared.Contracts/Submissions/Submissions.cs
- ess/src/API/EMBC.ESS/Managers/Submissions/SubmissionsManager.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Submissions/EvacuationFileTests.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.Files.cs
Clean up relevant business logic from controller to the manager.
> EMBCESSMOD-2457: remove EvacuationFileNotesQuery

- responders/src/UI/embc-responder/package-lock.json
- responders/src/UI/embc-responder/package.json
- responders/src/UI/embc-responder/src/app/material.module.ts
- responders/src/UI/embc-responder/src/styles/_variables.scss
- added flex
- updated container width
> Embcessmod 3153

- load-test/src/package.json
- load-test/src/src/registrant-portal-test.ts
- load-test/src/src/registrants/api/models/community-type.ts
- load-test/src/src/registrants/generators/evacuation-file.ts
- load-test/src/src/registrants/generators/needs-assessment.ts
- load-test/src/src/registrants/generators/pet.ts
- load-test/src/src/responder-portal-test.ts
- load-test/src/src/utilities.ts
bug fixes for data creation. Add flow to update an existing evacuation file as an existing registrant. Add responders authentication
> EMBCESSMOD-3190, EMBCESSMOD-3191: updates to registrant portal load tests

- load-test/src/.gitignore
- load-test/src/package.json
- load-test/src/src/benchmark-test.ts
- load-test/src/src/registrant-anonymous-test.ts
- load-test/src/src/registrant-existing-profile-test.ts
- load-test/src/src/registrant-new-profile-test.ts
- load-test/src/src/registrant-portal-scripts.ts
- load-test/src/src/responder-existing-registration-test.ts
- load-test/src/src/responder-new-registration-test.ts
- load-test/src/src/responder-portal-scripts.ts
- load-test/src/src/stress-test.ts
- load-test/src/src/utilities.ts
Further cleanup and improvements. Include additional output files.
> EMBCESSMOD-3386: Add stress test scenario

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
Show external file id if it exists.
Fix overlapping info icon.
Update completed paper based banner.
> EMBCESSMOD-3336: file dashboard header updates

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/essfile-security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/essfile-security-phrase.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.ts
No possible matches for paper based processing. No option to link for paper based files. Update verify security phrase back navigation. Fix possible matches sorting
> EMBCESSMOD-3327: link to file changes

- registrants/src/API/EMBC.Registrants.API/Controllers/EvacuationsController.cs
- registrants/src/UI/embc-registrant/package.json
Add missing cdk to package.json
> EMBCESSMOD-3369: fix api return type for evacuationFileDate.

- responders/src/UI/embc-responder/src/app/core/services/timeout.service.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/time-out-dialog/time-out-dialog.component.html
Fix typo
Fix issue where countdown timer was starting at 1:00 and then counting down from 3:59
> EMBCESSMOD-3274, EMBCESSMOD-3356: fix issue where session countdown stopped from moving the mouse

- ess/src/API/EMBC.ESS/Resources/Teams/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Teams/TeamRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Managers/AdminTests.cs
- responders/src/API/EMBC.Responders.API/Controllers/TeamsController.Members.cs
- responders/src/UI/embc-responder/src/app/feature-components/team/edit-team-member/edit-team-member.component.html
Add test to remove team member label. Some team repo cleanup.
> EMBCESSMOD-3119: Fix bug where front end isn't sending updated value when no label selected

- .github/workflows/cd-ess-backend.yml
- .github/workflows/cd-landing-page.yml
- .github/workflows/cd-oauth-server.yml
- .github/workflows/cd-pdf-generator.yml
- .github/workflows/cd-registrants-portal-api.yml
- .github/workflows/cd-registrants-portal-ui.yml
- .github/workflows/cd-responders-portal-api.yml
- .github/workflows/cd-responders-portal-ui.yml
- .github/workflows/cd-suppliers-portal-api.yml
- .github/workflows/cd-suppliers-portal-ui.yml
BREAKING CHANGE: trying to bump major version to 1.0.0
> EMBCESSMOD-2019: fix(all): version env var was not set correctly

- .github/workflows/cd-registrants-portal-api.yml
BREAKING CHANGE: bump to v1.0.0
> EMBCESSMOD2019: fix(registrants-portal-api): CD workflow was incorrect 

- registrants/src/UI/Caddyfile
- registrants/src/UI/Dockerfile
- responders/src/UI/Caddyfile
- responders/src/UI/Dockerfile
- suppliers/src/UI/Caddyfile
- suppliers/src/UI/Dockerfile
fix(): attempt to fix permissions
> EMBCESSMOD-2019: fix(): caddy config permissions

- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.cs
- registrants/src/API/EMBC.Registrants.API/Controllers/EvacuationsController.cs
Add external id and supplier info
> EMBCESSMOD-3577, EMBCESSMOD-3578: fixes for mapping support info

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/evacuation-details/evacuation-details.component.ts
- ESS File Dashboard - Link to Profile Display issue
- Create ESS File - Paper Based ESS File # is missing
> EMBCESSMOD-3563 & 3601

- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-table/assigned-community-table.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog/dialog.component.ts
fix encapsulation none causing table header dark backgrounds to cascade to all components
> EMBCESSMOD-3712

- responders/src/UI/embc-responder/src/app/core/api/services/registrations.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.html
fix case display of search names. Possible file matches show paper file number if there is one
> EMBCESSMOD-3667, EMBCESSMOD-3689

- responders/src/UI/embc-responder/src/app/feature-components/responder-dashboard/responder-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/responder-dashboard/responder-dashboard.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/review-support/review-support.component.ts
Minor style fixes to responder dashboard
> attempt print pdf fix for Aidan. 

- responders/src/API/EMBC.Responders.API/Controllers/ProfileController.cs
- responders/src/UI/embc-responder/src/app/app.component.ts
- responders/src/UI/embc-responder/src/app/shared/error-handling/access-denied/access-denied.component.html
- responders/src/UI/embc-responder/src/app/shared/error-handling/access-denied/access-denied.component.scss
show access denied dialog if no matching team member is found
> EMBCESSMOD-3351

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-adapter.service.ts
Add missing initials when creating profile from household member.
Fix Valid To font color when support is expired.
> EMBCESSMOD-2906, EMBCESSMOD-3166

- responders/src/UI/embc-responder/package.json
- responders/src/UI/embc-responder/src/app/core/api/api-configuration.ts
- responders/src/UI/embc-responder/src/app/core/api/models/registrant-profile-search-result.ts
- responders/src/UI/embc-responder/src/app/core/api/services/registrations.service.ts
- responders/src/UI/embc-responder/src/app/core/models/evacuee-search-results.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-details/ess-file-details.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/matched-essfiles/matched-essfiles.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.spec.ts
EMBCESSMOD-3844: No ID - Search Results
EMBCESSMOD-3807: Paper based ESS File# converted into Digital ESS File# automatically
> EMBCESSMOD-3845: Responder Portal - Evacuee Search - Cannot Retrieve Profile

- ess/src/API/EMBC.ESS/Managers/Events/Mappings.cs
- responders/src/API/EMBC.Responders.API/Services/EvacuationSearchService.cs
- responders/src/UI/embc-responder/src/app/core/api/api-configuration.ts
- responders/src/UI/embc-responder/src/app/core/api/models/evacuation-file-search-result.ts
- responders/src/UI/embc-responder/src/app/core/api/models/registrant-profile-search-result.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.ts
- shared/src/EMBC.ESS.Shared.Contracts/Events/Search.cs
-Added 'isAuthenticated' to profileResults
> EMBCESSMOD-3844: No ID - Search Results

- responders/src/UI/embc-responder/src/app/core/layout/header/header.component.html
- responders/src/UI/embc-responder/src/app/core/layout/header/header.component.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-details/ess-file-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/essfile-security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-id-verify/evacuee-id-verify.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-name-search/evacuee-name-search.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/registrant-link-dialog/registrant-link-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/view-assessment-dialog/view-assessment-dialog.component.html
Header style fixes. 
Date of birth display fixes. 
View supports minor text fix.
> EMBCESSMOD-2887, EMBCESSMOD-2938, EMBCESSMOD-3158, EMBCESSMOD-3398: minor style fixes

- responders/src/UI/embc-responder/src/app/feature-components/assigned-community/assigned-community-table/assigned-community-table.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/contact/contact.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-referral/support-referral.component.html
EMBCESSMOD-3850: Community Management - Content Update
EMBCESSMOD-3478: Wizard - Security Phrase - Masking Update
EMBCESSMOD-3927: Support Delivery - Supplier Notes - Content Update
EMBCESSMOD-3924: Wizard - Contact Details - Content Update
> Content updates

- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/bcsc-invite-dialog/bcsc-invite-dialog.component.html
- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/bcsc-invite-dialog/bcsc-invite-dialog.component.scss
- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/ess-file-dialog/ess-file-dialog.component.html
- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/ess-file-dialog/ess-file-dialog.component.scss
- registrants/src/UI/embc-registrant/src/app/core/layout/header/header.component.scss
- registrants/src/UI/embc-registrant/src/app/core/services/disableBack.guard.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/file-submission/file-submission.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-list/evacuation-file-list.component.ts
registrant portal - mobile layout fixes
> EMBCESSMOD-3877, EMBCESSMOD-3878, EMBCESSMOD-3879, EMBCESSMOD-3880

- registrants/src/UI/embc-registrant/src/app/app.component.html
- registrants/src/UI/embc-registrant/src/app/app.component.scss
caused by the scroll container having overflow: auto
> EMBCESSMOD-3886: registrant dropdown scroll issue

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/view-assessment-dialog/view-assessment-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/view-assessment-dialog/view-assessment-dialog.component.ts
EMBCESSMOD-3165: Household Members naming format
EMBCESSMOD-3169: Evacuation Details label issue
> EMBCESSMOD-2971, 2970: Needs Assessment fix, EMBCESSMOD-2925: Support period

- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.cs
- ess/src/API/EMBC.ESS/Resources/Evacuees/EvacueesRepository.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Suppliers/SupplierRepository.cs
- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Managers/TeamsManagerTests.cs
EMBCESSMOD-4088: send registration email only when creating a new registrant
EMBCESSMOD-3874: no email when completing a paper file
> multiple fixes

- ess/src/API/EMBC.ESS/Resources/Suppliers/SupplierRepository.cs
> EMBCESSMOD-4110: suppliers list query improvements

- responders/src/UI/embc-responder/src/app/core/models/wizard-type.model.ts
- responders/src/UI/embc-responder/src/app/core/services/compute/computeWizard.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.ts
- responders/src/UI/embc-responder/src/styles/styles.scss
Refactoring for this PR: https://github.com/bcgov/embc-ess-mod/pull/1498
> EMBCESSMOD-4113: Update wizard variables

- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/remote-search/remote-search.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/remote-search/remote-search.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/search-options/search-options.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/list-notes/list-notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/notes-components/notes/notes.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/address/address.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/address/address.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/evacuee-details/evacuee-details.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-notes/step-notes.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- responders/src/UI/embc-responder/src/app/unit-tests/mockRestriction.service.ts
- responders/src/UI/embc-responder/src/app/unit-tests/mockStepEvacueeProfile.service.ts
- responders/src/UI/embc-responder/src/app/unit-tests/mockStepNotes.service.ts
EMBCESSMOD-4470: Add Notes - Choose Pathway - Add Notes option is disabled for Expired task #
Unit Test cases
> EMBCESSMOD-4380: Add the ability to backdate supports from the start date of the task

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/search-registration/dashboard-activate.guard.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/search-registration/search-registration-routing.module.ts
> EMBCESSMOD-4461: ESS File is incorrectly displaying

- ess/src/API/EMBC.Tests.Integration.ESS/Managers/Events/SupportTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Resources/SupportTests.cs
- suppliers/src/UI/embc-supplier/src/app/fire-and-forget/submission/submission.component.ts
- suppliers/src/UI/embc-supplier/src/styles/styles.scss
Improve modal closing behavior
> EMBCESSMOD-4537: fix style bug preventing user from interacting with modals.

- ess/src/API/EMBC.ESS/Resources/Evacuees/Contract.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
Reverts bcgov/embc-ess-mod#1791
> Revert "Embcessmod 4652"

- ess/src/API/EMBC.ESS/Resources/Evacuees/Contract.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.cs
Reverts bcgov/embc-ess-mod#1792
> Revert "Revert "Embcessmod 4652""

- .github/workflows/cd-responders-portal-ui.yml
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-etransfer/support-etransfer.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-etransfer/support-etransfer.component.ts
Back Merging hotfix into master
> Hotfix embcessmod 4674

- ess/src/API/EMBC.ESS/Managers/Reports/ReportsManager.cs
- ess/src/API/EMBC.ESS/Resources/Reports/ReportRepository.cs
- responders/src/UI/embc-responder/src/app/feature-components/reporting/reporting.component.ts
- shared/src/EMBC.Utilities.Messaging/Grpc/Configuration.cs
- shared/src/EMBC.Utilities/Csv/CsvConverter.cs
Reverts bcgov/embc-ess-mod#1807
> Revert "Report performance improvements"

- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/DuplicateSupportComplianceCheck.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/ISupportComplianceStrategy.cs
Reverts bcgov/embc-ess-mod#1806
> Revert "fix: duplicate check to consider contained date range and minor perfomance improvements"

- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/DuplicateSupportComplianceCheck.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/ISupportComplianceStrategy.cs
Reverts bcgov/embc-ess-mod#1812
> Revert "Revert "fix: duplicate check to consider contained date range and minor perfomance improvements""

- ess/src/API/EMBC.ESS/Managers/Reports/ReportsManager.cs
- ess/src/API/EMBC.ESS/Resources/Reports/ReportRepository.cs
- responders/src/UI/embc-responder/src/app/feature-components/reporting/reporting.component.ts
- shared/src/EMBC.Utilities.Messaging/Grpc/Configuration.cs
- shared/src/EMBC.Utilities/Csv/CsvConverter.cs
Reverts bcgov/embc-ess-mod#1811
> Adding in again "Report performance improvements""

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.ts
Reverts bcgov/embc-ess-mod#1834
> Revert "EMBCESSMOD-4682: Added additiona logging - to be reverted as well"

- responders/src/UI/embc-responder/src/app/core/services/compute/computeWizard.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.ts
Reverts bcgov/embc-ess-mod#1833
> Revert "EMBCESSMOD-4682 - Adding logging to assiting with debugging TEST data…"

- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.ts
Reverts bcgov/embc-ess-mod#1825
> Revert "EMBCESSMOD-4682:  Removed the load of profile when loading ESS file a…"

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
Reverts bcgov/embc-ess-mod#1844
> Revert "EMBCESSMOD-4754 - Adding frontend warning for food-groceries & food-r…"

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
Reverts bcgov/embc-ess-mod#1848
> Revert "Revert "EMBCESSMOD-4754 - Adding frontend warning for food-groceries & food-r…""

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
Reverts bcgov/embc-ess-mod#1850
> Revert "Revert "Revert "EMBCESSMOD-4754 - Adding frontend warning for food-groceries & food-r…"""

- landing-page/src/html/index.html
EMBCESSMOD-4779 - Remove the banner in landing page
> EMBCESSMOD-4779 - Remove the banner in landing page

- landing-page/src/html/index.html
Reverts bcgov/embc-ess-mod#1863
> EMBCESSMOD-4779 -  Removing Banner again for Feb11

- tools/helm/era/.gitignore
- tools/helm/era/.helmignore
- tools/helm/era/Chart.yaml
- tools/helm/era/README.md
- tools/helm/era/templates/NOTES.txt
- tools/helm/era/templates/_configmap.tpl
- tools/helm/era/templates/_deployment.tpl
- tools/helm/era/templates/_helpers.tpl
- tools/helm/era/templates/_hpa.tpl
- tools/helm/era/templates/_netpol.tpl
- tools/helm/era/templates/_pdb.tpl
- tools/helm/era/templates/_route.tpl
- tools/helm/era/templates/_secret.tpl
- tools/helm/era/templates/_service.tpl
- tools/helm/era/templates/components.yaml
- tools/helm/era/templates/dp_pvc.yaml
- tools/helm/tools/.gitignore
- tools/helm/tools/.helmignore
- tools/helm/tools/Chart.yaml
- tools/helm/tools/README.md
- tools/helm/tools/templates/NOTES.txt
- tools/helm/tools/templates/dev-release-pipeline.yaml
- tools/helm/tools/templates/imagestreams.yaml
- tools/helm/tools/templates/prod-release-pipeline.yaml
- tools/helm/tools/templates/promote-image-task1.yml
- tools/helm/tools/templates/tag-image-task.yml
- tools/helm/tools/templates/test-release-pipeline.yaml
- tools/helm/tools/templates/training-release-pipeline.yaml
- tools/helm/tools/values.yaml
> EMBCESSMOD-4877: ERA helm charts

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/animals/animals.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members-pets/household-members-pets.component.ts
EMBCESSMOD-5037 EMBCESSMOD-5038
EMBCESSMOD-5039 EMBCESSMOD-5040
- Pet validation fixed;
- UI for pets/review pages fixed
> EMBCESSMOD-5037

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members-pets/household-members-pets.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members-pets/household-members-pets.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
EMBCESSMOD-5056, EMBCESSMOD-5056 
Responder: Not Started Validation fixed for Household members/Pets page
Responder: At least one person should be selected among Household Members
> EMBCESSMOD-5056: bug fixes

- registrants/src/UI/embc-registrant/src/app/core/api/models/person-details.ts
- registrants/src/UI/embc-registrant/src/app/core/model/needs.model.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.service.ts
EMBCESSMOD-5035, EMBCESSMOD-5036 -
Registrant  - Pets Validation fix for blank field
Registrant  - Family Information Validation fix for wizard
> EMBCESSMOD-5035, EMBCESSMOD-5036 - Pets/Family Validation

- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/view-assessment-dialog/view-assessment-dialog.component.html
EMBCESSMOD-5006 -"View Needs Assessment" - Household members/pets sections update with current structure
> EMBCESSMOD-5006: View Needs Assessment updates

- registrants/src/UI/embc-registrant/src/app/core/api/models/person-details.ts
- registrants/src/UI/embc-registrant/src/app/core/model/needs.model.ts
- registrants/src/UI/embc-registrant/src/app/core/services/customValidation.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/edit/edit.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.service.ts
EMBCESSMOD-5066 - Reverted changes for blank/space Pet title form and primary Registrant/Household Update
> EMBCESSMOD-5066: bug fixes

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/needs/needs.component.ts
Fix unselecting ShelterType when requireshelter is unchecked
-  make requiresShelterType required when requiresShelter is selected
> EMBCESSMOD-5108, EMBCESSMOD-5109, EMBCESSMOD-5110 Fix unselecting Shelter Type when requires shelter is unchecked

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.service.ts
: Fix support delivery form enable details when referral is selected
- EMBCESSMOD-5120: Change Needs Assessment => Needs
- EMBCESSMOD-5119: Shelter Allowance - Switch Between ETransfer/Referral
> EMBCESSMOD-5120: Enable Support Delivery referral details form when Referral is selected in Delivery  

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
EMBCESSMOD-5106: Fix spelling of shelterAllowance dialog message
> EMBCESSMOD-5106: Fix spelling of shelterAllowance dialog message

- registrants/src/API/EMBC.Registrants.API/Controllers/EvacuationsController.cs
- registrants/src/UI/embc-registrant/src/app/core/api/models.ts
- registrants/src/UI/embc-registrant/src/app/core/api/models/lodging-allowance-support.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/referral-details/referral-details.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/referral-details/referral-details.component.ts
Shelter Allowance Supports customized in registrant views
> EMBCESSMOD-5046 - Registrants : Shelter Allowance view adjustment

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/view-supports.component.ts
EMBCESSMOD-5004 - Lodging - Billeting Option disabled, Extend and Edit blocked for existing Supports of this type
> EMBCESSMOD-5004 - Billeting Option disabled

- registrants/src/UI/embc-registrant/src/app/core/model/needs.model.ts
- registrants/src/UI/embc-registrant/src/app/core/services/customValidation.service.ts
- registrants/src/UI/embc-registrant/src/app/core/services/formCreation.service.ts
- registrants/src/UI/embc-registrant/src/app/core/services/globalConstants.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/review/review.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/needs/needs.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
5109 - Fix automatically selecting incidents
5134 - update text
5132 - Change Shelter  Referral -> Shelter
5133 - Add description Household doesn't need assistance 
5135 - validate needs section and prevent going to next
> EMBCESSMOD-5109, EMBCESSMOD-5132, EMBCESSMOD-5133, EMBCESSMOD-5134, EMBCESSMOD-5135 

- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/identify-needs/identify-needs.component.html
EMBCESSMOD-5135 add validation error messages when at least one need is note selected
> EMBCESSMOD-5135 add validation error messages when atleast one need is note selected

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/select-support/select-support.component.ts
Shelter option removed from the list of Support Categories
> EMBCESSMOD-5131 - Shelter option removed from Support Categories list

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-overview/ess-file-overview.component.html
EMBCESSMOD-5129- ESS file overview- No needs identified message displayed
> EMBCESSMOD-5129- Ess file overview- No needs message

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-details/ess-file-details.component.html
EMBCESSMOD-5130
Label changed Needs Assessment -> Needs.
No needs message displayed
> EMBCESSMOD-5130 - Needs Assessment texts update

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/needs/needs.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/needs/needs.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard.component.spec.ts
- responders/src/UI/embc-responder/src/app/unit-tests/mockStepEssFile.service.ts
EMBCESSMOD-5146 Fix needs form to preserve the current form updates in the step ess file wizard
> EMBCESSMOD-5146 Fix needs form to preserve the current form updates in the step ess file wizard

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.service.ts
EMBCESSMOD-5153 fix infinite loop, and fix to not hide form immediately on entering a value in profile form
> EMBCESSMOD-5153 fix infinite loop, and fix to not hide form immediately on entering a value in profile form

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
> Merge R3.1.0 changes to R3.2.0 and resolve merge conflicts

- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment-mapping.service.ts
EMBCESSMOD-5154 - Pets displayed in ESS file review sections
> EMBCESSMOD-5154 - Pets displayed in ESS file review sections

- registrants/src/UI/embc-registrant/src/app/core/model/needs.model.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/review/review.component.ts
EMBCESSMOD-5168 Fix showing no need required message
> EMBCESSMOD-5168 Fix showing no need required message

- registrants/src/UI/embc-registrant/src/app/core/components/dialog/dialog.component.scss
- registrants/src/UI/embc-registrant/src/app/feature-components/review/review.component.scss
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information-pets/family-information-pets.component.scss
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.scss
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/pets/pets.component.scss
- registrants/src/UI/embc-registrant/src/app/sharedModules/outage-components/outage-banner/outage-banner.component.scss
- registrants/src/UI/embc-registrant/src/app/sharedModules/outage-components/outage-dialog/outage-dialog.component.scss
> EMBCESSMOD-5150: Fix/double img

- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/referral-details/referral-details.component.html
Removing he bold styling from Payee Full Name
> EMBCESSMOD-5179 - The bold formatting removal from Payee Full Name

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-delivery.component.html
EMBCESSMOD-5180, 81 -  ESS Rate Sheet window close button was missing; label update
> EMBCESSMOD-5180, 81 -  ESS Rate Sheet window close button missing

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/shelter-allowance/shelter-allowance.component.html
EMBCESSMOD-5184, 82 - Validation Display Added to Shelter Allowance;
Labels update
> EMBCESSMOD-5184: Validation Displayed; Labels Update

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-etransfer/support-etransfer.component.ts
EMBCESSMOD-5183 Fix showing data in the support draft form and able to save data
> EMBCESSMOD-5183 Fix showing data in the support draft form and able to save data

- ess/src/API/EMBC.ESS/Managers/Events/EvacuationFileLoader.cs
EMBCESSMOD-5086 - Self-serve support "Issued by" field update - Name of primary household member
> EMBCESSMOD-5086 - Self-serve support Issued by update

- registrants/src/UI/embc-registrant/src/app/core/services/globalConstants.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/identify-needs/identify-needs.component.html
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
Language Updates for Needs Assessment
> EMBCESSMOD-5207 - Language Updates for Needs Assessment

- registrants/src/UI/embc-registrant/src/app/core/model/needs.model.ts
- registrants/src/UI/embc-registrant/src/app/core/model/profile.model.ts
- registrants/src/UI/embc-registrant/src/app/core/services/formCreation.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment-mapping.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/review/review.component.ts
> EMBCESSMOD-5238: fixed registrant household member edit bug

- registrants/src/UI/embc-registrant/src/app/feature-components/file-submission/file-submission.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-card/evacuation-card.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.html
EMBCESSMOD-5071 - 'Supports Received' Language Update to 'Supports Issued'
> EMBCESSMOD-5071 - 'Supports Received' Language Update

- registrants/src/API/EMBC.Registrants.API/Controllers/EvacuationsController.cs
- registrants/src/API/EMBC.Registrants.API/Mappers/Mappings.cs
- registrants/src/UI/embc-registrant/src/app/core/api/models/support.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/dashboard/dashboard.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-data.service.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-list/evacuation-file-list.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/referral-details/referral-details.component.html
EMBCESSMOD-5072 - Registrant - Regular and Self-Serve e-Transfer differentiation
> EMBCESSMOD-5072: Registrant - Regular and Self-Serve e-Transfer differentiation

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
Update "Issued By" Field For SelfServe View
> EMBCESSMOD-5086 - Update "Issued By" Field For SelfServe

- ess/src/API/EMBC.ESS.Utilities.Cas/EMBC.ESS.Utilities.Cas.csproj
- ess/src/API/EMBC.ESS.Utilities.Dynamics/DataServiceContextEx.cs
- ess/src/API/EMBC.ESS.Utilities.Dynamics/DynamicsODataClientHandler.cs
- ess/src/API/EMBC.ESS.Utilities.Dynamics/EMBC.ESS.Utilities.Dynamics.csproj
- ess/src/API/EMBC.ESS.Utilities.Spatial/GeocoderApi/IGeocoderApi.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/AmountExceededSupportComplianceCheck.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/DuplicateSupportComplianceCheck.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/ISupportComplianceStrategy.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportProcessing/SelfServeSupportProcessingStrategy.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportingEngine.cs
- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.Supports.cs
- ess/src/API/EMBC.ESS/Resources/Evacuations/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Evacuations/EvacuationRepository.cs
- ess/src/API/EMBC.ESS/Resources/Reports/Contract.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Engines/Supporting/ComplianceTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Engines/Supporting/SelfServeTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Managers/Events/SupportTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Resources/EvacuationTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/TestHelper.cs
- ess/src/API/EMBC.Tests.Integration.ESS/WebAppTestBase.cs
- ess/src/API/EMBC.Tests.Unit.ESS/BogusEx.cs
- shared/src/EMBC.ESS.Shared.Contracts/Events/Supports.cs
- shared/src/EMBC.Utilities.Caching/EMBC.Utilities.Caching.csproj
- shared/src/EMBC.Utilities.Telemetry/EMBC.Utilities.Telemetry.csproj
- shared/src/EMBC.Utilities/Csv/CsvConverter.cs
- shared/src/EMBC.Utilities/EMBC.Utilities.csproj
- shared/src/EMBC.Utilities/Extensions/AssemblyEx.cs
- shared/src/EMBC.Utilities/Extensions/IEnumerableEx.cs
- shared/src/EMBC.Utilities/LambdaComparer.cs
- file association with task on self serve submission
- eligibility check to be false when needs are for referrals
- support duplicate check improvements
- opt out command handling
- continued conversion to net8 of utility projects
- duplicate support check for self-serve eligibility
> EMBCESSMOD-5077: various self serve fixes

- ess/src/API/EMBC.ESS/Engines/Supporting/Contract.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/SelfServe/SelfServeEtransferGenerator.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportProcessing/SelfServeSupportProcessingStrategy.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportingEngine.cs
- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.Supports.cs
- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.cs
- ess/src/API/EMBC.ESS/Resources/Evacuations/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Evacuations/EvacuationRepository.cs
- ess/src/API/EMBC.ESS/Resources/Evacuations/Mappings.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Managers/Events/EvacuationFileTests.cs
- registrants/src/API/EMBC.Registrants.API/Controllers/SupportsController.cs
- registrants/src/API/EMBC.Registrants.API/Mappers/Mappings.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.Files.cs
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- shared/src/EMBC.ESS.Shared.Contracts/Events/EvacuationFiles.cs
- EMBCESSMOD-5296: opt out is not saved
- EMBCESSMOD-5208: associate the signed in task for needs assessment
- EMBCESSMOD-5267: eligibility period calculation should be in UTC
> various bug fixes

- registrants/src/UI/embc-registrant/src/app/sharedModules/components/dashboard/dashboard.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-data.service.ts
EMBCESSMOD-5319, EMBCESSMOD-5320 - Banners fixed for ERA
> EMBCESSMOD-5319, EMBCESSMOD-5320 - Banners fixed for ERA

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
EMBCESSMOD-5323 - Comma added for Issued By field
> EMBCESSMOD-5323 - Comma added for Issued By field

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-supports/ess-file-supports.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/supports-table/supports-table.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/view-supports/supports-table/supports-table.component.ts
EMBCESSMOD-5325 - Self-Serve Italic font formatting   
EMBCESSMOD-5240 - Responder Review file includes Insurance Selection
> EMBCESSMOD-5240, EMBCESSMOD-5325 - Self-Serve Formatting and Insurance Selection

- registrants/src/UI/embc-registrant/src/app/core/components/dialog-components/self-serve-submissoin-dialog/self-serve-submission-dialog.component.scss
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-interac-e-transfer-form/self-serve-support-interac-e-transfer-form.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-form.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-restaurant-meals-info-dialog/self-serve-support-restaurant-meals-info-dialog.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-restaurant-meals-info-dialog/self-serve-support-restaurant-meals-info-dialog.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support.model.ts
- registrants/src/UI/embc-registrant/src/styles/styles.scss
- Fix showing red color checkbox for invalid checkbox
- show info modal for self serve support restaurant meals
- add astrix for interac e-transfer notification label
- make selected food text bold
- Fix showing correct action buttons at the botton of each step
- fix link underline in the self serve support confirmation modal
> EMBCESSMOD-5326, EMBCESSMOD-5327, EMBCESSMOD-5329, EMBCESSMOD-5340, EMBCESSMOD-5341 Fix Self serve support issues

- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-data.service.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-list/evacuation-file-list.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/existing-support-details/existing-support-details.component.ts
EMBCESSMOD-5314 - Banner text fixed for single/multiple evacuation files
Formatted issued by for Self-serve supports
> EMBCESSMOD-5314 - Banner text for Evacuees

- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-data.service.ts
EMBCESSMOD-5314 -Banner content revised for multiple ESS files
> EMBCESSMOD-5314 -Banner content revised for multiple ESS files

- registrants/src/UI/embc-registrant/src/app/core/services/componentCreation.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/review/review.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/secret/secret.component.html
5280 - Security Phrase updated to Security Word
> EMBCESSMOD-5280 - Security Phrase updated to Security Word

- registrants/src/UI/embc-registrant/src/app/feature-components/edit/edit.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/edit/edit.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/restriction/restriction.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/review/review.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/restriction-form/restriction-form.component.html
5277 - Restriction Language Updated
> EMBCESSMOD-5277 - Restriction Language Updated

- registrants/src/UI/embc-registrant/src/app/core/services/globalConstants.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/shelter-allowance/shelter-allowance.component.ts
Shelter Allowance Per Household Calculation
> Embcessmod-5366 - Shelter Allowance Per Household Calculation

- registrants/src/UI/embc-registrant/src/app/app-routing.module.ts
- registrants/src/UI/embc-registrant/src/app/core/layout/header/header.component.html
- registrants/src/UI/embc-registrant/src/app/core/layout/header/header.component.scss
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-confirm/self-serve-support-confirm.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-form.component.scss
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-review/self-serve-support-review.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/referral-details/referral-details.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/referral-details/referral-details.component.scss
Fix header account dropdown for mobile screen
- Fix table to show data in mobile screen
- DIsable clicking stepper header in self serve support
- Fix TM font -size
- Scroll to top on eligibility confirm view
> EMBCESSMOD-5377, EMBCESSMOD-5378, EMBCESSMOD-5379, EMBCESSMOD-5380 Fix responsive design issues

- ess/src/API/EMBC.ESS/Engines/Supporting/Contract.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/SelfServe/SelfServeSupportGenerator.cs
- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.Supports.cs
- ess/src/API/EMBC.ESS/Resources/Tasks/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Tasks/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Tasks/TaskRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/DynamicsTestData.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Engines/Supporting/SelfServeTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Managers/Events/SupportTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Resources/TaskTests.cs
- ess/src/API/EMBC.Tests.Unit.ESS/Engines/SelfServeSupportGenerationTests.cs
- EMBCESSMOD-5374: filter self serve supports by the task settings
EMBCESSMOD-5373: fixed file primary registrant check in optout handler
> EMBCESSMOD-5374, EMBCESSMOD-5373 bug fixes

- ess/src/API/EMBC.ESS/Managers/Events/Notifications/Templates/ETransferConfirmationTemplate.hbs
E-transfer email content updated
> EMBCESSMOD-5376 - E-transfer email content updated

- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.html
Shelter Allowance rate update for registrants
> EMBCESSMOD-5367 - Shelter Allowance rate update for registrants

- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/SelfServe/SelfServeSupportGenerator.cs
- ess/src/API/EMBC.Tests.Unit.ESS/Engines/SelfServeSupportGenerationTests.cs
EMBCESSMOD-5363 - BE SelfServe Support Shelter Allowance Calculations
> EMBCESSMOD-5363 - BE SelfServe Support Shelter Allowance Calculations

- ess/src/API/EMBC.ESS/Resources/Reports/Mappings.cs
EMBCESSMOD-5372 - Support Report - Lodging Language Updated; 
Shelter Allowance added to the list of Sub types
> EMBCESSMOD-5372 - Support Report Language and types update

- registrants/src/UI/embc-registrant/src/app/core/services/componentCreation.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-form.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-form.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-review/self-serve-support-review.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/dashboard/dashboard.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-list/evacuation-file-list.component.ts
EMBCESSMOD-5217 - remove confirm restriction step
- EMBCESSMOD-5385 - Fix validation in self serve review step
- EMBCESSMOD-5396 - Prevent sending more than one request to backend when you click a submit button on self-serve
- Fix loading diameter, color
> EMBCESSMOD-5217, EMBCESSMOD-5385, EMBCESSMOD-5396 - Remove confirm restriction step, Fix validation in self serve review step

- ess/src/API/EMBC.ESS/EMBC.ESS.csproj
- ess/src/API/EMBC.ESS/Engines/Supporting/Contract.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/SelfServe/SelfServeSupportGenerator.cs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportProcessing/SelfServeSupportEligibilityStrategy.cs
- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.Supports.cs
- ess/src/API/EMBC.ESS/Resources/Evacuations/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Evacuations/EvacuationRepository.cs
- ess/src/API/EMBC.ESS/Resources/Evacuations/Mappings.cs
- ess/src/API/EMBC.Tests.Integration.ESS/DynamicsTestData.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Engines/Supporting/SelfServeTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Managers/Events/SupportTests.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Resources/EvacuationTests.cs
- EMBCESSMOD-5384: associate eligibility with eligible supports
- EMBCESSMOD-5374: correctly filter eligible self serve support
> EMBCESSMOD-5384: associate eligibility with eligible supports

- responders/src/UI/embc-responder/src/app/core/api/services/registrations.service.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-details/ess-file-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/essfile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/essfile-security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/essfile-security-phrase.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/security-phrase-card/security-phrase-card.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/evacuee-profile-dashboard.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-profile-dashboard/possible-matched-essfiles/possible-matched-essfiles.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-id-verify/evacuee-id-verify.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-name-search/evacuee-name-search.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/zero-file-result/zero-file-result.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/ess-file-review/ess-file-review.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/profile-review/profile-review.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.component.spec.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-ess-file/step-ess-file.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/wizard-data.service.ts
- responders/src/UI/embc-responder/src/app/unit-tests/mockStepEssFile.service.ts
Responder Portal Updates:
Update Restriction Language;
Remove Restriction Status;
Change Security Phrase to Security Word;
EMBCESSMOD-5114, EMBCESSMOD-5185, EMBCESSMOD-5174
> EMBCESSMOD-5174: Responder Portal Updates

- registrants/src/UI/embc-registrant/src/app/core/services/globalConstants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/needs/needs.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/shelter-allowance-delivery/shelter-allowance-delivery.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog/dialog.component.html
EMBCESSMOD-5399 - Text update for Shelter Allowance calculations;
EMBCESSMOD-5401 - Bold formatting for Informational Popup;
EMBCESSMOD-5241 - Text update for Needs Assessment Page;
EMBCESSMOD-5316 - Evacuee Support - Shelter Allowance wording;
> EMBCESSMOD- 5399,5401,5241,5316 

- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-interac-e-transfer-form/self-serve-support-interac-e-transfer-form.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-card/evacuation-card.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-card/evacuation-card.component.scss
EMBCESSMOD-5415: Fix showing required error message for confirm mobile
> EMBCESSMOD-5404: fix active status column alignment

- registrants/src/UI/embc-registrant/src/app/app-routing.module.ts
- registrants/src/UI/embc-registrant/src/app/core/services/disableBack.guard.fn.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-form.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support.routes.ts
EMBCESSMOD-5403: Fix margin bottom for stepper component on self serve support details form
> EMBCESSMOD-5383, EMBCESSMOD-5403:  Fix prevent navigation using back button on self serve support confirm component

- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-interac-e-transfer-form/self-serve-support-interac-e-transfer-form.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.ts
- EMBCESSMOD-5415 fix error message interac e-transfer recipient name
> EMBCESSMOD-5421-disable partially supported food type and show a message to indicate its not supported via self-serve

- registrants/src/UI/embc-registrant/src/app/core/services/globalConstants.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
EMBCESSMOD-5425 - Duplicate household members warning popup
> EMBCESSMOD-5425 - Duplicate household members warning

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.service.ts
- responders/src/UI/embc-responder/src/styles/styles.scss
- Fix margin of mat-form-field
- FIx image icon for case note list
> EMBCESSMOD-5441: Fix date field validation

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-details/ess-file-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/ess-file-details/ess-file-details.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-security-phrase/essfile-security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/access-reason-gate-dialog/access-reason-gate-dialog.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/profile-security-questions/profile-security-questions.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.html
EMBCESSMOD-5445 - Wrong label displayed for Proceed Button
EMBCESSMOD-5446 - Back to Evacuee Search button displayed instead of Back button
EMBCESSMOD-5447 - Security Word tab - Security Phrase is displayed
EMBCESSMOD-5448 - Security Word was not displayed in ESS File Details
> EMBCESSMOD-5445,5446,5447,5448 - Display issues in Responder Portal

- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.html
> EMBCESSMOD-5443: Self serve shelter allowance - remove household checkbox section

- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/evacuee-search-results/evacuee-search-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/security-phrase/security-phrase.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/profile-components/restriction/restriction.component.html
EMBCESSMOD-5458 - Security Phrase updated to Security Word.
EMBCESSMOD-5459 - Restriction page - 'No' option - period is missing.
EMBCESSMOD-5460 - Search Results - ESS File and Profile Results formatted.
> EMBCESSMOD-5458,59,60 - Minor updates in registrant portal

- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
Duplicate Household member warning added for main applicant information
> EMBCESSMOD-5455 - Duplicate Household member warning 

- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.html
> EMBCESSMOD-5461 - Supports Issued color used incorrect

- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/essfile-dashboard/household-member/household-member.component.scss
EMBCESSMOD-5464 - Link to this Profile styling incorrect
> EMBCESSMOD-5464 - Link to this Profile styling incorrect

- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/referral-details/referral-details.component.scss
- Fix title color of expansion panel
- make the text bold in the support expansion review message
> EMBCESSMOD-5475, EMBCESSMOD-5476 Fix title color of expansion panel

- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
EMBCESSMOD-5478 - Duplicate Household Member not working correctly
> EMBCESSMOD-5478 - Duplicate Household Member not working correctly

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-referral/support-referral.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-referral/support-referral.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-referral/support-referral.component.ts
- Fix showing loading on refresh suppliers list
> EMBCESSMOD-5441: Fix supplier list autocomplete dropdown component styles

- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
EMBCESSMOD-5486 - Gender removed from duplicated household member check
> EMBCESSMOD-5486 - Gender removed from duplicated household member check

- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/family-information/family-information.component.ts
EMBCESSMOD-5487 - Scroll to top of household member added after the form closure
> EMBCESSMOD-5487 - Scroll to top of household member added after the form closure

- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.component.ts
- Fix resetting identify Needs form for active state ESS file updates
- Fix showing correct wording in the success popup
> EMBCESSMOD-5482, EMBCESSMOD-5483, EMBCESSMOD-5484 Fix Cancel button label

- responders/src/UI/embc-responder/src/app/app.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/supplier-management/suppliers-list/suppliers-table/suppliers-table.component.scss
- responders/src/UI/embc-responder/src/styles/styles.scss
- Fix active and inactive switch components color
- Fix showing time icon for input type time
> EMBCESSMOD-5441: Fix showing startup loading screen

- registrants/src/API/EMBC.Registrants.API/Mappers/Mappings.cs
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/dashboard/dashboard.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-data.service.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-list/evacuation-file-list.component.ts
EMBCESSMOD-5444 - Registrant Portal - Revised Display Rules for Profile Banners
> EMBCESSMOD-5444 - Registrant Portal - Revised Display Rules for Profile Banners

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.service.ts
EMBCESSMOD-5427 - Responder - Add Household Members - Duplicate Check
> EMBCESSMOD-5427 - Responder - Add Household Members - Duplicate Check

- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-file-data.service.ts
- Fix hasActiveSupports to not include cancelled or void supports
> EMBCESSMOD-5511, 5516 Fix showing UnavailableOneTimeUse message

- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/referral-details/referral-details.component.scss
- registrants/src/UI/embc-registrant/src/styles/styles.scss
EMBCESSMOD-5494 - View Support button fixed;
Word-break fixed for mobile version in supports.
> EMBCESSMOD-5494 - View Support button/Word-break style fixed

- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.scss
EMBCESSMOD-5481 - Update your details - CSS div Fix
> EMBCESSMOD-5481 - Update your details - CSS div Fix

- registrants/src/UI/embc-registrant/src/app/core/services/formCreation.service.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/needs-assessment/needs-assessment.component.ts
- registrants/src/UI/embc-registrant/src/app/sharedModules/components/evacuation-file/evacuation-details/evacuation-details.component.scss
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/identify-needs/identify-needs.component.html
- registrants/src/UI/embc-registrant/src/app/sharedModules/forms/needs-assessment-forms/identify-needs/identify-needs.component.ts
- registrants/src/UI/embc-registrant/src/styles/styles.scss
> EMBCESSMOD-5513: Fix resetting needs form values when updating the active ess file needs assessment

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.ts
EMBCESSMOD-5528 - Household Members & Pets page display incomplete icon
> EMBCESSMOD-5528 - Household Members & Pets page display incomplete icon

- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/ess-file-components/household-members/household-members.component.scss
EMBCESSMOD-5527 - Add Household Member button display not correct
> EMBCESSMOD-5527 - Add Household Member button display not correct

- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/ReferralPrinting/Views/ShelterAllowance/ShelterAllowanceAdditionalInfoPartial.hbs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/ReferralPrinting/Views/ShelterAllowance/ShelterAllowanceSupplierPartial.hbs
EMBCESSMOD-5531 - Spelling issues for the shelter allowance referral.
> EMBCESSMOD-5531 - Spelling issues for the shelter allowance referral.

- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-details-form/self-serve-support-details-form.component.html
EMBCESSMOD-5539 - Incidentals Spelling mistake
> EMBCESSMOD-5539 - Incidentals Spelling mistake

- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/shelter-allowance/shelter-allowance.component.ts
EMBCESSMOD-5551 - Responder Portal - Shelter Allowance Rates Update
> EMBCESSMOD-5551: Responder Portal - Shelter Allowance Rates Update

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/billeting-delivery/billeting-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/group-lodging-delivery/group-lodging-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/shelter-allowance-delivery/shelter-allowance-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/support-etransfer/support-etransfer.component.html
EMBCESSMOD-5044 - AutoComplete is off for Referral and e-Trasnfer Contact details.
> EMBCESSMOD-5044 - AutoComplete is off for Referral and e-Trasnfer Contact details.

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/billeting-delivery/billeting-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/shelter-allowance-delivery/shelter-allowance-delivery.component.html
EMBCESSMOD-5044 - Autocomplete disabled for Full Name
> EMBCESSMOD-5044 - Autocomplete disabled for Full Name

- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/ReferralPrinting/Views/Css.hbs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/ReferralPrinting/Views/ShelterAllowance/ShelterAllowanceAdditionalInfoPartial.hbs
- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/ReferralPrinting/Views/ShelterAllowance/ShelterAllowanceSupplierPartial.hbs
Shelter Allowance Referral Form Content Updates
> EMBCESSMOD-5593 - Shelter Allowance Referral Form Content Updates

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
EMBCESSMOD-4980 - Support start date and time automatically set to the next available slot based on the current ESS file (+ 1 minute) or defaults to current date/time
> EMBCESSMOD-4980 - Support start date and time automatically set to the next available slot

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/shelter-allowance-delivery/shelter-allowance-delivery.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/shelter-allowance-delivery/shelter-allowance-delivery.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-delivery/delivery-types/shelter-allowance-delivery/shelter-allowance-delivery.component.ts
Shelter Allowance Support Creation Updates - Payee Name taken from primary registrant information
> EMBCESSMOD-5596 - Shelter Allowance Support Creation Updates

- responders/src/UI/embc-responder/src/app/core/services/evacuee-profile.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/ess-files-results/ess-files-results.component.scss
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.html
- responders/src/UI/embc-responder/src/app/feature-components/search/evacuee-search/profile-results/profile-results.component.scss
EMBCESSMOD-5636: BUG: e-Transfer eligible case sensitive
EMBCESSMOD-5637:  BUG: Completed ESS File shows e-Transfer Eligible
> EMBCESSMOD-5076: bug fixes

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
EMBCESSMOD-5638/41 - Default Support Start Date excludes Voided Supports Calculations and Applies to Clone Support
> Default Support StartDate Calculations

- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.html
- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.scss
ticket: https://jag.gov.bc.ca/jira/browse/EMBCESSMOD-5590
> EMBCESSMOD-5590 - Supplier Portal - File size warning

- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-form.component.ts
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-review/self-serve-support-review.component.html
- registrants/src/UI/embc-registrant/src/app/feature-components/self-serve-support/self-serve-support-review/self-serve-support-review.component.ts
- responders/src/UI/embc-responder/proxy.dev.support.conf.json
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/details-type/shelter-allowance/shelter-allowance.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.service.ts
Added attestation when shelter allowance is selected in the Responders and Registrants portal to confirm that shelter allowance has not already been given.
> DEVOPS-26: Shelter Allowance Attestation for Responders & Registrants

- suppliers/src/API/EMBC.Suppliers.API/appsettings.json
- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.html
- suppliers/src/UI/embc-supplier/src/app/core/components/fileUpload/fileUpload.component.ts
- suppliers/src/UI/embc-supplier/src/app/core/components/toasts/toasts-container.component.html
- suppliers/src/UI/embc-supplier/src/app/core/components/toasts/toasts-container.component.scss
- suppliers/src/UI/embc-supplier/src/app/core/services/globalConstants.ts
- suppliers/src/UI/embc-supplier/src/app/core/services/toast.service.ts
Improved Toast messaging across application, increased maximum payload size.
> EMBCESSMOD-5590: Max File Size Increase

- ess/src/API/EMBC.ESS.Utilities.Dynamics/Connected Services/Dynamics/ConnectedService.json
Independent PR to update the Dynamics Connected Service code. Also updated ConnectedService.json to reflect new Dynamics URL.
> DEVOPS-43: Update Dynamics Connected Service code

- ess/src/API/Dockerfile
- registrants/src/API/Dockerfile
- responders/src/API/Dockerfile
- shared/src/EMBC.ESS.Shared.Contracts/EMBC.ESS.Shared.Contracts.csproj
- shared/src/EMBC.Utilities.Hosting/EMBC.Utilities.Hosting.csproj
- shared/src/EMBC.Utilities.Telemetry/EMBC.Utilities.Telemetry.csproj
- shared/src/EMBC.Utilities/EMBC - Backup.Utilities.csproj
- shared/src/EMBC.Utilities/EMBC.Utilities.csproj
> Package-Upgrades: Bump package versions for ESS

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.html
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
Removed validator checking for duplicate supports in paper files.
> EMBCESSMOD-4764: Responders Portal - Paper based file error

- .github/workflows/zap-scans.yml
- ess/src/API/EMBC.ESS.Host/EMBC.ESS.Host.csproj
- ess/src/API/EMBC.ESS.Utilities.Cas/EMBC.ESS.Utilities.Cas.csproj
- ess/src/API/EMBC.ESS.Utilities.Dynamics/EMBC.ESS.Utilities.Dynamics.csproj
- ess/src/API/EMBC.ESS.Utilities.Spatial/EMBC.ESS.Utilities.Spatial.csproj
- ess/src/API/EMBC.Tests.Integration.ESS/EMBC.Tests.Integration.ESS.csproj
- ess/src/API/EMBC.Tests.Unit.ESS/EMBC.Tests.Unit.ESS.csproj
- load-test/src/package-lock.json
- load-test/src/package.json
- oauth-server/src/API/OAuthServer/OAuthServer.csproj
- registrants/src/API/EMBC.Registrants.API/EMBC.Registrants.API.csproj
- registrants/src/API/EMBC.Tests.Unit.Registrants.API/EMBC.Tests.Unit.Registrants.API.csproj
- responders/src/API/EMBC.Responders.API/EMBC.Responders.API.csproj
- responders/src/API/EMBC.Tests.Unit.Responders.API/EMBC.Tests.Unit.Responders.API.csproj
- responders/src/UI/embc-responder/package-lock.json
- shared/src/EMBC.Utilities.Hosting/EMBC.Utilities.Hosting.csproj
- shared/src/EMBC.Utilities.Messaging/EMBC.Utilities.Messaging.csproj
- shared/src/EMBC.Utilities.Telemetry/EMBC.Utilities.Telemetry.csproj
- suppliers/src/API/EMBC.Suppliers.API/EMBC.Suppliers.API.csproj
- suppliers/src/API/EMBC.Tests.Integration.Suppliers.API/EMBC.Tests.Integration.Suppliers.API.csproj
- suppliers/src/API/EMBC.Tests.Unit.Suppliers.API/EMBC.Tests.Unit.Suppliers.API.csproj
- suppliers/src/UI/embc-supplier/package-lock.json
Bumped package versions to take care of dependabot alerts.
> ESS-Package-Upgrades: Bump various package versions

- ess/src/API/EMBC.ESS/Resources/Payments/PaymentRepository.cs
Ticket: https://emcr.atlassian.net/browse/DEVOPS-47
Added check to PaymentRepository on the CreatePaymentRequest method to throw an exception if the payee is a minor.
> DEVOPS-47: Do not create payment transaction for minors

- ess/src/API/EMBC.ESS.Utilities.Dynamics/DynamicsODataClientHandler.cs
- ess/src/API/EMBC.ESS.Utilities.Dynamics/EMBC.ESS.Utilities.Dynamics.csproj
- ess/src/API/EMBC.Tests.Integration.ESS/EMBC.Tests.Integration.ESS.csproj
- registrants/src/API/EMBC.Registrants.API/EMBC.Registrants.API.csproj
PR to resolve dependabot issues including resolving a breaking version of Microsoft OData.
> Dependabot-PR-Resolution: Resolve dependabot issues

- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.Supports.cs
- ess/src/API/EMBC.ESS/Resources/Supports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- responders/src/API/EMBC.Responders.API/Controllers/SupportsController.cs
- shared/src/EMBC.ESS.Shared.Contracts/Events/Supports.cs
- shared/src/EMBC.Utilities/Extensions/DiceCoefficientExtension.cs
- shared/src/EMBC.Utilities/Extensions/DoubleMetaphoneExtension.cs
- shared/src/EMBC.Utilities/Extensions/LevenshteinDistanceExtension.cs
- shared/src/EMBC.Utilities/Extensions/LongestCommonSubsequenceExtension.cs
Draft pull request for API changes. Current issue with symlinks not finding binaries.
> DEVOPS-36: Fuzzy match household members across tasks and files

- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.Supports.cs
- ess/src/API/EMBC.ESS/Resources/Supports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- responders/src/API/EMBC.Responders.API/Controllers/SupportsController.cs
- responders/src/UI/embc-responder/src/app/core/api/fn/supports/supports-get-duplicate-supports.ts
- responders/src/UI/embc-responder/src/app/core/api/models/support-delivery.ts
- responders/src/UI/embc-responder/src/app/core/api/services/supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- shared/src/EMBC.ESS.Shared.Contracts/Events/Supports.cs
- shared/src/EMBC.Utilities/Extensions/StringSimilarityExtension.cs
Demo video here: https://drive.google.com/file/d/1vURRLZG4AGba-F3g9anCAX7pTOk0ijEQ/view?usp=sharing
JIRA ticket: https://emcr.atlassian.net/browse/DEVOPS-36
This PR improves upon the previously committed code to enable fuzzy searching of potential duplicate supports across ESS tasks and files. Please see comments in code for detailed description of how the application processes these requests.
> DEVOPS-36: Fuzzy Matching for Duplicate Supports

- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
Fixed issue with support mapping function.
> DEVOPS-36: Update support mapping function

- registrants/src/UI/embc-registrant/src/app/core/services/login.service.ts
Ticket: https://emcr.atlassian.net/browse/DEVOPS-140
Fixed validation check on registrants portal for verified registration.
> DEVOPS-140: Fix verified registraion path validation

- ess/src/API/EMBC.ESS/Engines/Supporting/SupportGeneration/SelfServe/SelfServeEtransferGenerator.cs
- ess/src/API/EMBC.ESS/Managers/Events/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Supports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Supports/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- responders/src/API/EMBC.Responders.API/Controllers/RegistrationsController.Supports.cs
- responders/src/UI/embc-responder/src/app/core/api/models/househod-member-dto.ts
- responders/src/UI/embc-responder/src/app/core/api/models/support.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- shared/src/EMBC.ESS.Shared.Contracts/Events/Supports.cs
Updated per feedback from internal QA. Now pulls evacuee information directly from household member data and serves to the front end.
> DEVOPS-36: Update data delivery and modal

- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- shared/src/EMBC.Utilities/Extensions/StringSimilarityExtension.cs
Tweaked algorithm execution and weighting decisions with fuzzy matching.
> DEVOPS-36: Tweak algorithms and weights, lock object

- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
Updated supports query to check across similar support types (Shelter - Hotel/Motel/Campground and Shelter - Group Lodging will now be caught)
> DEVOPS-36: Compare supports across similar support types

- ess/src/API/EMBC.ESS/Resources/Reports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Reports/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Reports/ReportRepository.cs
DEVOPS-262 - Payee information added to the Support Report
> DEVOPS-262 - Payee information added to the Support Report

- ess/src/API/EMBC.ESS/Resources/Reports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Reports/Mappings.cs
DEVOPS-178: Support report - Status and Status Reason columns added
- Contract and Mapping Updated
> DEVOPS-178: Support report - Status and Status Reason columns added

- registrants/src/API/EMBC.Registrants.API/Mappers/Mappings.cs
- registrants/src/API/EMBC.Tests.Unit.Registrants.API/Profiles/MappingTests.cs
- shared/src/EMBC.Utilities/Extensions/StringExtension.cs
310 - Registrant Postal code formatting - Always uppercase, no spaces
> 310 - Registrant Postal code formatting - Always uppercase, no spaces

- responders/src/UI/embc-responder/src/app/feature-components/responder-dashboard/responder-dashboard.component.html
- responders/src/UI/embc-responder/src/app/shared/components/toggle-side-nav/toggle-side-nav.component.html
- responders/src/UI/embc-responder/src/app/shared/components/top-nav-menu/top-nav-menu.component.html
ESS Resource Hub link/text update
> EMCR-225 - ESS Resource Hub link update

- .github/workflows/devskim.yml
- ess/src/API/EMBC.ESS.Utilities.Dynamics/Connected Services/Dynamics/ConnectedService.json
- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.Supports.cs
- ess/src/API/EMBC.ESS/Resources/Reports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Reports/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Supports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Supports/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- responders/src/API/EMBC.Responders.API/Controllers/ReportsController.cs
- responders/src/API/EMBC.Responders.API/Controllers/SupportsController.cs
- responders/src/UI/embc-responder/src/app/core/api/fn/supports/supports-add-duplicate-support-conflict.ts
- responders/src/UI/embc-responder/src/app/core/api/fn/supports/supports-get-duplicate-supports.ts
- responders/src/UI/embc-responder/src/app/core/api/services/supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- shared/src/EMBC.ESS.Shared.Contracts/Events/Supports.cs
- shared/src/EMBC.ESS.Shared.Contracts/Reports.cs
This reverts commit 711a0294afd5067d5234854189884d7381c6b6bd for a popup counter
> Reapply "Support Conflict Popup Counter"

- ess/src/API/EMBC.ESS/Resources/Reports/ReportRepository.cs
The service is temporarily unavailable. Please try again later - Fix 1
>  Support/Evacuee Query Fix #1

- ess/src/API/EMBC.ESS/Managers/Events/EventsManager.Supports.cs
- ess/src/API/EMBC.ESS/Resources/Reports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Reports/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Supports/Contract.cs
- ess/src/API/EMBC.ESS/Resources/Supports/Mappings.cs
- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- responders/src/API/EMBC.Responders.API/Controllers/ReportsController.cs
- responders/src/API/EMBC.Responders.API/Controllers/SupportsController.cs
- responders/src/UI/embc-responder/src/app/core/api/fn/supports/supports-add-duplicate-support-conflict.ts
- responders/src/UI/embc-responder/src/app/core/api/models/conflict-message-scenario.ts
- responders/src/UI/embc-responder/src/app/core/api/services/supports.service.ts
- responders/src/UI/embc-responder/src/app/core/models/dialog-content.model.ts
- responders/src/UI/embc-responder/src/app/core/models/duplicate-support.model.ts
- responders/src/UI/embc-responder/src/app/core/models/wizard-type.model.ts
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/step-supports/step-supports.service.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/information-dialog/information-dialog.component.html
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/information-dialog/information-dialog.component.ts
- shared/src/EMBC.ESS.Shared.Contracts/Events/Supports.cs
- shared/src/EMBC.ESS.Shared.Contracts/Events/Tasks.cs
- shared/src/EMBC.ESS.Shared.Contracts/Reports.cs
Revert "Merge pull request #2638 for Duplicated Support Popup"
> Revert "Merge pull request #2638 for Duplicated Support Popup"

- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/DuplicateSupportComplianceCheck.cs
- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- ess/src/API/EMBC.Tests.Integration.ESS/Engines/Supporting/ComplianceTests.cs
- responders/src/UI/embc-responder/src/app/core/services/global-constants.ts
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
- responders/src/UI/embc-responder/src/app/shared/components/dialog-components/information-dialog/information-dialog.component.ts
- shared/src/EMBC.ESS.Shared.Contracts/Events/Supports.cs
Added Important Case Note
Added Flag to QE for duplicated supports
> ERA-74 - Duplicate Support Addition

- ess/src/API/EMBC.ESS/Engines/Supporting/SupportCompliance/DuplicateSupportComplianceCheck.cs
- ess/src/API/EMBC.ESS/Resources/Supports/SupportRepository.cs
- responders/src/UI/embc-responder/src/app/feature-components/wizard/support-components/support-details/support-details.component.ts
ERA-74 - Format update for the Support Period
> Format update for the Support Period

- responders/src/API/EMBC.Responders.API/Controllers/SuppliersController.cs
- Added data needed in mapping
- Fix endpoint http://localhost:6200/api/Suppliers/e12b53c5-3365-4612-99c6-7405c258ae96
> ERA-108:  Supplier Management screen does not load
